using System.Text.Json;

namespace Dalagab.Omega;

public sealed class MarketplacePlugin
{
    public string Author { get; init; } = string.Empty;
    public IReadOnlyList<string> Authors { get; init; } = [];
    public IReadOnlyList<string> EffectiveAuthors => Authors.Count > 0 ? Authors : MarketplaceAuthorRules.Split(Author);
    public string Name { get; init; } = string.Empty;
    public string InternalName { get; init; } = string.Empty;
    // Stable catalog identity shared by every repository variant of the same plugin.
    // Zero means the plugin came from a legacy JSON/live Dalamud overlay without a database id.
    public long CatalogPluginId { get; init; }
    public string Punchline { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
    public string Changelog { get; init; } = string.Empty;
    public string AssemblyVersionText { get; init; } = "0.0.0.0";
    public Version AssemblyVersion => Version.TryParse(AssemblyVersionText, out var version) ? version : new Version(0, 0);
    public string? TestingAssemblyVersionText { get; init; }
    public Version? TestingAssemblyVersion => Version.TryParse(TestingAssemblyVersionText, out var version) ? version : null;
    public int DalamudApiLevel { get; init; }
    public int? TestingDalamudApiLevel { get; init; }
    public string ApplicableVersion { get; init; } = "any";
    public string? MinimumDalamudVersionText { get; init; }
    public Version? MinimumDalamudVersion => Version.TryParse(MinimumDalamudVersionText, out var version) ? version : null;
    public string RepoUrl { get; init; } = string.Empty;
    public string DownloadLinkInstall { get; init; } = string.Empty;
    public string DownloadLinkUpdate { get; init; } = string.Empty;
    public string DownloadLinkTesting { get; init; } = string.Empty;
    public string IconUrl { get; init; } = string.Empty;
    public IReadOnlyList<string> ImageUrls { get; init; } = [];
    public IReadOnlyList<string> Tags { get; init; } = [];
    public IReadOnlyList<string> CategoryTags { get; init; } = [];
    public long DownloadCount { get; init; }
    public long LastUpdate { get; init; }
    public bool IsHide { get; init; }
    public bool IsTestingExclusive { get; init; }
    public string Dip17Channel { get; init; } = string.Empty;
    public string SourceName { get; init; } = string.Empty;
    public string SourceUrl { get; init; } = string.Empty;
    public bool SourceIsOfficial { get; init; }

    // Static security intelligence generated by Omega's server-side Sigmascope engine for this exact catalog variant.
    public string SecurityStatus { get; set; } = string.Empty;
    public string SecurityScannedAtUtcText { get; set; } = string.Empty;
    public DateTimeOffset? SecurityScannedAtUtc => DateTimeOffset.TryParse(SecurityScannedAtUtcText, out var parsed) ? parsed : null;
    public string SecurityArtifactSha256 { get; set; } = string.Empty;
    public string SigmascopeVersion { get; set; } = string.Empty;
    public string SecurityHighestSeverity { get; set; } = "none";
    public int SecurityInformationalCount { get; set; }
    public int SecurityCautionCount { get; set; }
    public int SecurityHighCount { get; set; }
    public int SecurityCriticalCount { get; set; }
    public IReadOnlyList<string> SecurityCapabilities { get; set; } = [];
    public string SecurityAutomationLevel { get; set; } = "none";
    public IReadOnlyList<MarketplaceAutomationCapability> SecurityAutomationCapabilities { get; set; } = [];
    public IReadOnlyList<MarketplaceSecurityFinding> SecurityFindings { get; set; } = [];
    public IReadOnlyList<MarketplaceDependency> SecurityDependencies { get; set; } = [];
    public int SecurityDependencyTotalCount { get; set; }
    public int SecurityKnownAdvisoryCount { get; set; }
    public string SecurityKnownAdvisoryHighestSeverity { get; set; } = "none";
    public int SecurityRiskScore { get; set; }
    public bool HasKnownAtRiskDependency => SecurityKnownAdvisoryCount > 0;
    public bool SecuritySourceAvailable { get; set; }
    public string SecuritySourceRepository { get; set; } = string.Empty;
    public string SecuritySourceCommit { get; set; } = string.Empty;
    // Independent review/source coverage. This is not a security severity or probability.
    public int SecuritySourceAttributionConfidence { get; set; }
    public IReadOnlyList<string> SecuritySourceAttributionBasis { get; set; } = [];
    public string SecurityReviewCoverageLabel { get; set; } = "Unresolved";
    public bool SecuritySourceToBinaryVerified { get; set; }
    public string SecurityError { get; set; } = string.Empty;
    public bool HasCompletedSecurityScan => SecurityStatus.Equals("complete", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Live Dalamud/repository manifests own runtime metadata, while the downloaded Omega database
    /// owns Sigmascope annotations. Security may cross that boundary only for the same plugin,
    /// package version, and repository identity so a stale scan is never attached to a newer build.
    /// </summary>
    public bool CanInheritSecurityProjectionFrom(MarketplacePlugin databaseVariant)
    {
        if (databaseVariant is null ||
            !InternalName.Equals(databaseVariant.InternalName, StringComparison.OrdinalIgnoreCase) ||
            !AssemblyVersionText.Equals(databaseVariant.AssemblyVersionText, StringComparison.OrdinalIgnoreCase))
            return false;

        if (SourceIsOfficial || databaseVariant.SourceIsOfficial)
            return SourceIsOfficial && databaseVariant.SourceIsOfficial;

        var liveSource = NormalizeRepositoryUrl(SourceUrl);
        var databaseSource = NormalizeRepositoryUrl(databaseVariant.SourceUrl);
        return liveSource.Length > 0 && liveSource.Equals(databaseSource, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Replaces only server-generated security annotations. Passing null clears any previously
    /// inherited projection, which prevents an old live overlay object retaining stale evidence
    /// after the database or plugin version changes.
    /// </summary>
    public void ApplySecurityProjectionFrom(MarketplacePlugin? source)
    {
        SecurityStatus = source?.SecurityStatus ?? string.Empty;
        SecurityScannedAtUtcText = source?.SecurityScannedAtUtcText ?? string.Empty;
        SecurityArtifactSha256 = source?.SecurityArtifactSha256 ?? string.Empty;
        SigmascopeVersion = source?.SigmascopeVersion ?? string.Empty;
        SecurityHighestSeverity = source?.SecurityHighestSeverity ?? "none";
        SecurityInformationalCount = source?.SecurityInformationalCount ?? 0;
        SecurityCautionCount = source?.SecurityCautionCount ?? 0;
        SecurityHighCount = source?.SecurityHighCount ?? 0;
        SecurityCriticalCount = source?.SecurityCriticalCount ?? 0;
        SecurityCapabilities = source?.SecurityCapabilities ?? [];
        SecurityAutomationLevel = source?.SecurityAutomationLevel ?? "none";
        SecurityAutomationCapabilities = source?.SecurityAutomationCapabilities ?? [];
        SecurityFindings = source?.SecurityFindings ?? [];
        SecurityDependencies = source?.SecurityDependencies ?? [];
        SecurityDependencyTotalCount = source?.SecurityDependencyTotalCount ?? 0;
        SecurityKnownAdvisoryCount = source?.SecurityKnownAdvisoryCount ?? 0;
        SecurityKnownAdvisoryHighestSeverity = source?.SecurityKnownAdvisoryHighestSeverity ?? "none";
        SecurityRiskScore = source?.SecurityRiskScore ?? 0;
        SecuritySourceAvailable = source?.SecuritySourceAvailable ?? false;
        SecuritySourceRepository = source?.SecuritySourceRepository ?? string.Empty;
        SecuritySourceCommit = source?.SecuritySourceCommit ?? string.Empty;
        SecuritySourceAttributionConfidence = source?.SecuritySourceAttributionConfidence ?? 0;
        SecuritySourceAttributionBasis = source?.SecuritySourceAttributionBasis ?? [];
        SecurityReviewCoverageLabel = source?.SecurityReviewCoverageLabel ?? "Unresolved";
        SecuritySourceToBinaryVerified = source?.SecuritySourceToBinaryVerified ?? false;
        SecurityError = source?.SecurityError ?? string.Empty;
    }

    private static string NormalizeRepositoryUrl(string? value)
        => (value ?? string.Empty).Trim().TrimEnd('/');

    // Optional Omega extension fields. Standard Dalamud manifests do not need these.
    public int? OmegaMinimumApiLevel { get; init; }
    public int? OmegaMaximumApiLevel { get; init; }
    public IReadOnlyList<string> OmegaCategories { get; init; } = [];
    public string OmegaWebsiteUrl { get; init; } = string.Empty;
    public string OmegaWebsiteTitle { get; init; } = string.Empty;
    public string OmegaWebsiteDescription { get; init; } = string.Empty;
    public string OmegaWebsiteReadmeExcerpt { get; init; } = string.Empty;
    public IReadOnlyList<string> OmegaWebsiteImageUrls { get; init; } = [];
    public string OmegaBannerUrl { get; init; } = string.Empty;
    public IReadOnlyList<MarketplaceProjectLink> OmegaProjectLinks { get; init; } = [];
    public bool OmegaEnriched { get; init; }
    public bool OmegaIsAdultContent { get; init; }

    public int HighestKnownApiLevel => new[]
    {
        DalamudApiLevel,
        TestingDalamudApiLevel ?? 0,
        OmegaMaximumApiLevel ?? 0,
    }.Max();

    public IReadOnlyList<string> EffectiveCategories => CategoryTags
        .Concat(OmegaCategories)
        .Distinct(StringComparer.OrdinalIgnoreCase)
        .OrderBy(x => x, StringComparer.OrdinalIgnoreCase)
        .ToArray();

    public bool SupportsApiLevel(int currentApi, bool allowTesting)
    {
        if (HasCurrentApiBuild(currentApi, allowTesting, out _))
            return true;

        return OmegaMinimumApiLevel is not null &&
               OmegaMaximumApiLevel is not null &&
               currentApi >= OmegaMinimumApiLevel &&
               currentApi <= OmegaMaximumApiLevel;
    }

    public int DisplayApiLevel(int currentApi, bool allowTesting)
        => SupportsApiLevel(currentApi, allowTesting) ? currentApi : HighestKnownApiLevel;

    public bool IsUnmaintained(int currentApi)
        => HighestKnownApiLevel > 0 && currentApi - HighestKnownApiLevel >= 3;

    public bool HasCurrentApiBuild(int currentApi, bool allowTesting, out bool useTesting)
    {
        useTesting = false;
        if (!IsTestingExclusive && DalamudApiLevel == currentApi && !string.IsNullOrWhiteSpace(DownloadLinkInstall))
            return true;

        if (allowTesting && TestingDalamudApiLevel == currentApi && TestingAssemblyVersion is not null && !string.IsNullOrWhiteSpace(DownloadLinkTesting))
        {
            useTesting = true;
            return true;
        }

        if (IsTestingExclusive && TestingDalamudApiLevel == currentApi && !string.IsNullOrWhiteSpace(DownloadLinkTesting))
        {
            useTesting = true;
            return true;
        }

        return false;
    }

    public string GetCompatibilityText(int currentApi, Version currentDalamudVersion, bool allowTesting)
    {
        if (MinimumDalamudVersion is not null && MinimumDalamudVersion > currentDalamudVersion)
            return $"Needs Dalamud {MinimumDalamudVersion}+";

        if (HasCurrentApiBuild(currentApi, allowTesting, out var testing))
            return testing ? $"API {currentApi} testing" : $"API {currentApi} compatible";

        if (OmegaMinimumApiLevel is not null && OmegaMaximumApiLevel is not null &&
            currentApi >= OmegaMinimumApiLevel && currentApi <= OmegaMaximumApiLevel)
            return $"API {currentApi} declared compatible";

        return HighestKnownApiLevel switch
        {
            0 => "API unknown",
            var api when api < currentApi => $"Outdated (max API {api})",
            var api when api > currentApi => $"Requires newer API {api}",
            _ => $"API {currentApi} build unavailable",
        };
    }

    public static MarketplacePlugin FromJson(JsonElement element, RepositorySource source)
    {
        return new MarketplacePlugin
        {
            Author = ReadString(element, "Author"),
            Authors = ReadStrings(element, "OmegaAuthors"),
            Name = ReadString(element, "Name"),
            InternalName = ReadString(element, "InternalName"),
            Punchline = ReadString(element, "Punchline"),
            Description = ReadString(element, "Description"),
            Changelog = ReadString(element, "Changelog"),
            AssemblyVersionText = ReadString(element, "AssemblyVersion", "0.0.0.0"),
            TestingAssemblyVersionText = ReadNullableString(element, "TestingAssemblyVersion"),
            DalamudApiLevel = ReadInt(element, "DalamudApiLevel"),
            TestingDalamudApiLevel = ReadNullableInt(element, "TestingDalamudApiLevel"),
            ApplicableVersion = ReadString(element, "ApplicableVersion", "any"),
            MinimumDalamudVersionText = ReadNullableString(element, "MinimumDalamudVersion"),
            RepoUrl = ReadString(element, "RepoUrl"),
            DownloadLinkInstall = ReadString(element, "DownloadLinkInstall"),
            DownloadLinkUpdate = ReadString(element, "DownloadLinkUpdate"),
            DownloadLinkTesting = ReadString(element, "DownloadLinkTesting"),
            IconUrl = ReadString(element, "IconUrl"),
            ImageUrls = ReadStrings(element, "ImageUrls"),
            Tags = ReadStrings(element, "Tags"),
            CategoryTags = ReadStrings(element, "CategoryTags"),
            DownloadCount = ReadLong(element, "DownloadCount"),
            LastUpdate = ReadLong(element, "LastUpdate", "LastUpdated"),
            IsHide = ReadBool(element, "IsHide"),
            IsTestingExclusive = ReadBool(element, "IsTestingExclusive"),
            Dip17Channel = ReadString(element, "_Dip17Channel"),
            SourceName = source.Name,
            SourceUrl = source.Url,
            SourceIsOfficial = source.IsOfficial,
            OmegaMinimumApiLevel = ReadNullableInt(element, "OmegaMinimumApiLevel"),
            OmegaMaximumApiLevel = ReadNullableInt(element, "OmegaMaximumApiLevel"),
            OmegaCategories = ReadStrings(element, "OmegaCategories"),
            OmegaWebsiteUrl = ReadString(element, "OmegaWebsiteUrl"),
            OmegaWebsiteTitle = ReadString(element, "OmegaWebsiteTitle"),
            OmegaWebsiteDescription = ReadString(element, "OmegaWebsiteDescription"),
            OmegaWebsiteReadmeExcerpt = ReadString(element, "OmegaWebsiteReadmeExcerpt"),
            OmegaWebsiteImageUrls = ReadStrings(element, "OmegaWebsiteImageUrls"),
            OmegaBannerUrl = ReadString(element, "OmegaBannerUrl"),
            OmegaProjectLinks = ReadProjectLinks(element, "OmegaProjectLinks"),
            OmegaEnriched = ReadBool(element, "OmegaEnriched"),
            OmegaIsAdultContent = ReadBool(element, "OmegaIsAdultContent"),
        };
    }

    private static bool TryGet(JsonElement element, string name, out JsonElement value)
    {
        if (element.TryGetProperty(name, out value))
            return true;

        foreach (var property in element.EnumerateObject())
        {
            if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                value = property.Value;
                return true;
            }
        }

        value = default;
        return false;
    }

    private static string ReadString(JsonElement element, string name, string fallback = "")
    {
        if (!TryGet(element, name, out var value))
            return fallback;
        return value.ValueKind switch
        {
            JsonValueKind.String => value.GetString() ?? fallback,
            JsonValueKind.Number => value.ToString(),
            _ => fallback,
        };
    }

    private static string? ReadNullableString(JsonElement element, string name)
        => TryGet(element, name, out var value) && value.ValueKind != JsonValueKind.Null ? ReadString(element, name) : null;

    private static int ReadInt(JsonElement element, string name)
        => ReadNullableInt(element, name) ?? 0;

    private static int? ReadNullableInt(JsonElement element, string name)
    {
        if (!TryGet(element, name, out var value) || value.ValueKind == JsonValueKind.Null)
            return null;
        if (value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out var number))
            return number;
        if (value.ValueKind == JsonValueKind.String && int.TryParse(value.GetString(), out number))
            return number;
        return null;
    }

    private static long ReadLong(JsonElement element, params string[] names)
    {
        foreach (var name in names)
        {
            if (!TryGet(element, name, out var value))
                continue;
            if (value.ValueKind == JsonValueKind.Number && value.TryGetInt64(out var number))
                return number;
            if (value.ValueKind == JsonValueKind.String && long.TryParse(value.GetString(), out number))
                return number;
        }

        return 0;
    }

    private static bool ReadBool(JsonElement element, string name)
    {
        if (!TryGet(element, name, out var value))
            return false;
        if (value.ValueKind is JsonValueKind.True or JsonValueKind.False)
            return value.GetBoolean();
        if (value.ValueKind == JsonValueKind.String && bool.TryParse(value.GetString(), out var flag))
            return flag;
        return false;
    }


    private static IReadOnlyList<MarketplaceProjectLink> ReadProjectLinks(JsonElement element, string name)
    {
        if (!TryGet(element, name, out var value) || value.ValueKind != JsonValueKind.Array)
            return [];
        return value.EnumerateArray()
            .Where(x => x.ValueKind == JsonValueKind.Object)
            .Select(x => new MarketplaceProjectLink(
                ReadString(x, "Kind"),
                ReadString(x, "Label"),
                ReadString(x, "Url")))
            .Where(x => !string.IsNullOrWhiteSpace(x.Kind) && !string.IsNullOrWhiteSpace(x.Url))
            .Take(8)
            .ToArray();
    }

    private static IReadOnlyList<string> ReadStrings(JsonElement element, string name)
    {
        if (!TryGet(element, name, out var value) || value.ValueKind != JsonValueKind.Array)
            return [];
        return value.EnumerateArray()
            .Where(x => x.ValueKind == JsonValueKind.String)
            .Select(x => x.GetString())
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Cast<string>()
            .ToArray();
    }
}
