// SPDX-License-Identifier: MIT-0
// Generator.cs — consumes the manifest produced by Inspector and emits
// shape-only C# stub code for the InterdimensionalRift.DalamudShim project.
// One .cs file is written per namespace (and one extra .cs for the global
// usings, suppressions, etc.). Generated code goes under <shim>/Generated/.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using DalaInspect;

namespace DalaInspect;

public sealed class Generator
{
    private readonly string _shimRoot;
    private readonly string _dalamudPath;
    private readonly string _generatedRoot;
    private readonly Dictionary<string, TypeShape> _byFullName = new(StringComparer.Ordinal);
    private readonly HashSet<string> _missingTypeWarnings = new(StringComparer.Ordinal);

    public Generator(string shimRoot, string dalamudPath)
    {
        _shimRoot = shimRoot;
        _dalamudPath = dalamudPath;
        _generatedRoot = Path.Combine(_shimRoot, "Generated");
    }

    public void Emit(Manifest manifest)
    {
        Directory.CreateDirectory(_generatedRoot);

        // Index by full name for nested-type lookup during emit.
        foreach (var t in manifest.Types)
        {
            _byFullName[t.FullName] = t;
        }

        // Group by namespace; within a namespace, top-level types are
        // processed first and nested types are emitted inside their parents.
        var byNs = manifest.Types
            .GroupBy(t => t.Namespace ?? string.Empty)
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        // Wipe previous generated code.
        foreach (var f in Directory.GetFiles(_generatedRoot, "*.cs"))
        {
            File.Delete(f);
        }

        // 1) Global usings / suppressions file
        WriteGlobalUsings(manifest);

        // 2) One .cs per namespace
        foreach (var g in byNs)
        {
            var sb = new StringBuilder();
            EmitNamespace(sb, g.Key, g.OrderBy(t => t, TypeOrder.Comparer).ToList());
            var fileName = MakeFileName(g.Key);
            File.WriteAllText(Path.Combine(_generatedRoot, fileName), sb.ToString());
        }

        // 3) Drop a manifest-descriptor file so the project knows the manifest
        // is up to date with the source DLL version.
        var notePath = Path.Combine(_generatedRoot, "GeneratedAssemblyInfo.cs");
        File.WriteAllText(notePath,
            "// Auto-generated descriptor of the source DLL this shim mirrors.\n" +
            $"// Source: {Path.GetFileName(_dalamudPath)} (version {manifest.AssemblyVersion})\n" +
            $"// Generated: {DateTimeOffset.UtcNow:yyyy-MM-ddTHH:mm:ssZ}\n" +
            $"[assembly: System.Reflection.AssemblyMetadata(\"DalamudShim.SourceAssembly\", \"{Path.GetFileName(_dalamudPath)}\")]\n" +
            $"[assembly: System.Reflection.AssemblyMetadata(\"DalamudShim.SourceAssemblyVersion\", \"{manifest.AssemblyVersion}\")]\n");

        if (_missingTypeWarnings.Count > 0)
        {
            Console.WriteLine($"  warnings      : {string.Join(", ", _missingTypeWarnings.OrderBy(s => s))}");
        }
    }

    private string MakeFileName(string ns)
    {
        if (string.IsNullOrEmpty(ns)) return "Global.cs";
        // Each segment that contains a dot stays as-is in the file name.
        // For the file system we replace '.' with '_' to keep things
        // portable; the namespace declaration inside the file is still
        // written as dot-separated.
        return ns.Replace('.', '_') + ".cs";
    }

    private void WriteGlobalUsings(Manifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is auto-generated by DalaInspect/Generator from the");
        sb.AppendLine($"// real Dalamud.dll ({Path.GetFileName(_dalamudPath)} v{manifest.AssemblyVersion}).");
        sb.AppendLine("// Do not edit by hand; re-run the generator to refresh.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("global using System;");
        sb.AppendLine("global using System.Collections;");
        sb.AppendLine("global using System.Collections.Generic;");
        sb.AppendLine("global using System.Threading;");
        sb.AppendLine("global using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("#pragma warning disable CS0067 // unused events");
        sb.AppendLine("#pragma warning disable CS0169 // unused field");
        sb.AppendLine("#pragma warning disable CS0414 // assigned but unused");
        sb.AppendLine("#pragma warning disable CS0649 // unassigned field");
        sb.AppendLine("#pragma warning disable CS1591 // missing XML doc");
        File.WriteAllText(Path.Combine(_generatedRoot, "GlobalUsings.cs"), sb.ToString());
    }

    private void EmitNamespace(StringBuilder sb, string ns, List<TypeShape> types)
    {
        // Suppression / header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Namespace {ns} from real {Path.GetFileName(_dalamudPath)}.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace declaration
        if (string.IsNullOrEmpty(ns))
        {
            // no namespace block
        }
        else
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        // Collect referenced namespaces for `using` directives.
        var usedNs = new SortedSet<string>(StringComparer.Ordinal);
        usedNs.UnionWith(RequiredNamespacesFor(types));

        foreach (var u in usedNs)
        {
            sb.Append("using ").Append(u).AppendLine(";");
        }
        if (usedNs.Count > 0) sb.AppendLine();

        // Emit top-level types (those with no DeclaringType).
        var topLevel = types.Where(t => t.DeclaringType is null).ToList();
        foreach (var t in topLevel)
        {
            EmitType(sb, t, types, indent: 0);
            sb.AppendLine();
        }
    }

    private IEnumerable<string> RequiredNamespacesFor(List<TypeShape> types)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var t in types)
        {
            foreach (var u in CollectNamespaces(t, includeGlobal: false))
            {
                if (string.IsNullOrEmpty(u)) continue;
                if (u == t.Namespace) continue; // already inside this ns
                if (u.StartsWith(t.Namespace + ".", StringComparison.Ordinal)) continue;
                seen.Add(u);
            }
        }
        return seen;
    }

    private IEnumerable<string> CollectNamespaces(TypeShape t, bool includeGlobal)
    {
        if (t.BaseType is not null) foreach (var u in NamespaceOf(t.BaseType)) yield return u;
        foreach (var i in t.Interfaces) foreach (var u in NamespaceOf(i)) yield return u;
        if (t.EnumUnderlyingType is not null) foreach (var u in NamespaceOf(t.EnumUnderlyingType)) yield return u;
        foreach (var c in t.GenericConstraints)
        {
            foreach (var ct in c.ConstraintTypes)
            {
                foreach (var u in NamespaceOf(ct)) yield return u;
            }
        }
        foreach (var m in t.Members)
        {
            if (m.ReturnType is not null) foreach (var u in NamespaceOf(m.ReturnType)) yield return u;
            if (m.PropertyType is not null) foreach (var u in NamespaceOf(m.PropertyType)) yield return u;
            if (m.FieldType is not null) foreach (var u in NamespaceOf(m.FieldType)) yield return u;
            if (m.EventType is not null) foreach (var u in NamespaceOf(m.EventType)) yield return u;
            if (m.EventHandlerType is not null) foreach (var u in NamespaceOf(m.EventHandlerType)) yield return u;
            foreach (var p in m.Parameters)
            {
                foreach (var u in NamespaceOf(p.Type)) yield return u;
            }
            foreach (var c in m.GenericConstraints)
            {
                foreach (var ct in c.ConstraintTypes)
                {
                    foreach (var u in NamespaceOf(ct)) yield return u;
                }
            }
        }
    }

    private static IEnumerable<string> NamespaceOf(string typeRef)
    {
        if (string.IsNullOrEmpty(typeRef)) yield break;
        // Strip generics, arrays, pointers, by-ref, etc.
        var s = typeRef;
        s = StripGenericArgs(s, out _);
        s = s.TrimEnd('&', '*');
        s = StripArray(s);
        if (s.StartsWith("ref ", StringComparison.Ordinal)) s = s.Substring(4);
        s = s.Trim();
        if (s.StartsWith("global::", StringComparison.Ordinal)) s = s.Substring("global::".Length);

        // Special primitives that don't need a using.
        switch (s)
        {
            case "void":
            case "object":
            case "string":
            case "bool":
            case "byte":
            case "sbyte":
            case "short":
            case "ushort":
            case "int":
            case "uint":
            case "long":
            case "ulong":
            case "float":
            case "double":
            case "decimal":
            case "char":
            case "nint":
            case "nuint":
                yield break;
        }

        // Nested types: take the outermost type's namespace.
        var plus = s.IndexOf('+');
        if (plus > 0) s = s.Substring(0, plus);

        var dot = s.LastIndexOf('.');
        if (dot <= 0) yield break;
        yield return s.Substring(0, dot);
    }

    private static string StripArray(string s)
    {
        // Strip trailing [...] dimensions.
        while (s.EndsWith("]", StringComparison.Ordinal))
        {
            var open = s.LastIndexOf('[');
            if (open < 0) break;
            s = s.Substring(0, open);
        }
        return s;
    }

    private static string StripGenericArgs(string s, out int depth)
    {
        depth = 0;
        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            var c = s[i];
            if (c == '<')
            {
                depth++;
                continue;
            }
            if (c == '>')
            {
                depth--;
                continue;
            }
            if (depth == 0) sb.Append(c);
        }
        return sb.ToString();
    }

    private void EmitType(StringBuilder sb, TypeShape t, List<TypeShape> siblings, int indent)
    {
        var pad = new string(' ', indent * 4);

        // Delegates are a single declaration, not a body.
        if (t.Kind == "delegate")
        {
            EmitDelegateSignature(sb, t, indent);
            return;
        }

        // Type declaration
        EmitTypeHeader(sb, t, indent);

        sb.AppendLine();
        sb.Append(pad).AppendLine("{");

        // Emit nested types first (delegates, enums, classes, etc. that
        // live inside this type). The parent's members may forward-reference
        // them; the C# compiler handles that. Nested delegates are emitted
        // as full declarations inside the parent body.
        var nested = siblings.Where(s => s.DeclaringType == t.FullName).OrderBy(s => s, TypeOrder.Comparer).ToList();
        var innerPad = new string(' ', (indent + 1) * 4);
        foreach (var n in nested)
        {
            if (n.Kind == "delegate")
            {
                EmitDelegateSignature(sb, n, indent + 1);
            }
            else if (n.Kind == "enum")
            {
                EmitTypeHeader(sb, n, indent + 1);
                sb.AppendLine();
                sb.Append(innerPad).AppendLine("{");
                EmitEnumMembers(sb, n, indent + 2);
                sb.Append(innerPad).AppendLine("}");
                sb.AppendLine();
            }
            else
            {
                EmitType(sb, n, siblings, indent + 1);
            }
            sb.AppendLine();
        }

        switch (t.Kind)
        {
            case "enum":
                EmitEnumMembers(sb, t, indent + 1);
                break;
            case "interface":
                EmitInterfaceMembers(sb, t, siblings, indent + 1);
                break;
            default:
                EmitClassMembers(sb, t, siblings, indent + 1);
                break;
        }

        sb.Append(pad).AppendLine("}");
    }

    private void EmitTypeHeader(StringBuilder sb, TypeShape t, int indent)
    {
        var pad = new string(' ', indent * 4);
        var access = t.IsPublic || t.IsNested || t.IsSealed || t.IsAbstract ? "public" : "internal";
        var modifiers = new List<string>();
        if (t.IsSealed && t.Kind == "class") modifiers.Add("sealed");
        if (t.IsAbstract && t.Kind == "class") modifiers.Add("abstract");
        var modifierStr = modifiers.Count > 0 ? " " + string.Join(" ", modifiers) : string.Empty;
        var keyword = t.Kind switch
        {
            "interface" => "interface",
            "struct" => "struct",
            "enum" => "enum",
            "delegate" => "delegate",
            _ => "class",
        };

        sb.Append(pad).Append(access).Append(modifierStr).Append(' ').Append(keyword).Append(' ').Append(NameWithGenerics(t));

        if (t.Kind != "enum" && t.Kind != "delegate")
        {
            // base + interfaces
            var bases = new List<string>();
            if (!string.IsNullOrEmpty(t.BaseType) && t.BaseType != "System.Object" && t.BaseType != "object")
            {
                // System.ValueType is the implicit base of every struct
                // and isn't a valid C# base. Same for System.Enum.
                if (t.BaseType is not "System.ValueType" and not "System.Enum" and not "ValueType" and not "Enum")
                {
                    bases.Add(RefName(t.BaseType!));
                }
            }
            foreach (var i in t.Interfaces)
            {
                // Skip System.Object / System.ValueType / System.Enum — they
                // get inherited; System.ValueType isn't a valid interface
                // in C# (it would need to be `where T : struct`).
                if (i is "System.Object" or "object" or "System.ValueType" or "System.Enum" or "ValueType") continue;
                bases.Add(RefName(i));
            }
            if (bases.Count > 0)
            {
                sb.Append(" : ").Append(string.Join(", ", bases));
            }
        }
        else if (t.Kind == "enum" && !string.IsNullOrEmpty(t.EnumUnderlyingType))
        {
            var ut = t.EnumUnderlyingType!;
            // Convert common underlying type names to C# aliases
            sb.Append(" : ").Append(RefName(ut));
        }

        // Generic type parameter constraints
        foreach (var gc in t.GenericConstraints)
        {
            var where = FormatWhereClause(gc);
            if (where is not null) sb.Append(' ').Append(where);
        }
    }

    private string NameWithGenerics(TypeShape t)
    {
        var name = StripArity(t.Name);
        if (t.GenericParams.Count == 0) return name;
        return $"{name}<{string.Join(", ", t.GenericParams)}>";
    }

    private static string StripArity(string s)
    {
        var tick = s.IndexOf('`');
        if (tick <= 0) return s;
        int i = tick + 1;
        while (i < s.Length && char.IsDigit(s[i])) i++;
        return s.Substring(0, tick) + s.Substring(i);
    }

    private string? FormatWhereClause(GenericConstraint gc)
    {
        if (gc.ConstraintTypes.Count == 0 && (gc.Attributes.Count == 0 || (gc.Attributes.Count == 1 && gc.Attributes[0] == "none")))
        {
            return null;
        }
        var parts = new List<string>();
        // Map the metadata-level `ValueType` constraint (often captured
        // by MetadataLoadContext as `System.ValueType` in the constraints
        // list) to C#'s `struct` keyword.
        bool hasStruct = gc.Attributes.Contains("struct") || gc.ConstraintTypes.Any(c => c is "System.ValueType" or "ValueType");
        if (gc.Attributes.Contains("class")) parts.Add("class");
        else if (hasStruct) parts.Add("struct");
        // `notnull` and `struct` are mutually exclusive in C#.
        if (gc.Attributes.Contains("notnull") && !hasStruct && !gc.Attributes.Contains("class")) parts.Add("notnull");
        // C# requires the order: class|struct|notnull, base types, interfaces, new()
        var baseTypes = new List<string>();
        var interfaces = new List<string>();
        foreach (var ct in gc.ConstraintTypes)
        {
            var s = ct;
            // System.ValueType and ValueType -> skip (we already emitted struct).
            if (s is "System.ValueType" or "ValueType") continue;
            // System.Enum is a value type itself; C# requires both `struct`
            // and `Enum` in the constraint list. We already added `struct`
            // if needed, so add `Enum` to baseTypes.
            if (s == "System.Enum" || s.EndsWith(".Enum"))
            {
                if (!baseTypes.Contains("System.Enum")) baseTypes.Add("System.Enum");
                continue;
            }
            // `System.Delegate` is a valid (rare) C# constraint.
            if (s == "System.Delegate") { baseTypes.Add("System.Delegate"); continue; }
            if (s == "System.Attribute" || s.EndsWith(".Attribute")) { interfaces.Add(s); continue; }
            if (s == "System.MulticastDelegate" || s.EndsWith(".MulticastDelegate")) { continue; }
            // Heuristic: anything starting with "I" and capital letter is an interface.
            if (s.Length > 1 && s[^1] != ']' && s.Split('.').Last().Length > 1 && char.IsUpper(s.Split('.').Last()[0]) && (s.Split('.').Last().StartsWith("I") || s.Contains("+")))
            {
                interfaces.Add(s);
            }
            else
            {
                baseTypes.Add(s);
            }
        }
        parts.AddRange(baseTypes);
        parts.AddRange(interfaces);
        if (gc.Attributes.Contains("new()") && !hasStruct) parts.Add("new()");
        return $"where {gc.Name} : {string.Join(", ", parts)}";
    }

    private void EmitEnumMembers(StringBuilder sb, TypeShape t, int indent)
    {
        var pad = new string(' ', indent * 4);
        foreach (var v in t.EnumValues)
        {
            sb.Append(pad).Append(v.Name).Append(" = ").Append(v.Value).AppendLine(",");
        }
    }

    private void EmitDelegateSignature(StringBuilder sb, TypeShape t, int indent)
    {
        var pad = new string(' ', indent * 4);
        // Find the Invoke method to extract return type + parameters
        var invoke = t.Members.FirstOrDefault(m => m.Kind == "method" && m.Name == "Invoke");
        var ret = RefName(invoke?.ReturnType ?? "void");
        var ps = invoke?.Parameters ?? new List<ParamShape>();
        // Delegate generic params live on the delegate TYPE, not the
        // Invoke method (the method inherits them as a member of a
        // generic type).
        var genericParams = t.GenericParams;
        var genericCstr = t.GenericConstraints;
        // Strip arity marker from the delegate's name (e.g. `Foo`1` -> `Foo`).
        var typeName = t.Name;
        var tick = typeName.IndexOf('`');
        if (tick > 0)
        {
            int i = tick + 1;
            while (i < typeName.Length && char.IsDigit(typeName[i])) i++;
            typeName = typeName.Substring(0, tick) + typeName.Substring(i);
        }
        var nameWithGenerics = genericParams.Count == 0
            ? typeName
            : $"{typeName}<{string.Join(", ", genericParams)}>";
        // Mark unsafe if the signature has pointer types.
        var hasUnsafe = (invoke?.ReturnType?.Contains('*') ?? false) || ps.Any(p => p.Type.Contains('*'));
        var unsafePrefix = hasUnsafe ? "unsafe " : string.Empty;
        sb.Append(pad).Append("public ").Append(unsafePrefix).Append("delegate ").Append(ret).Append(' ').Append(nameWithGenerics).Append('(');
        sb.Append(string.Join(", ", ps.Select(FormatParam)));
        sb.Append(')');
        foreach (var gc in genericCstr)
        {
            var where = FormatWhereClause(gc);
            if (where is not null) sb.Append(' ').Append(where);
        }
        sb.AppendLine(";");
    }

    private void EmitInterfaceMembers(StringBuilder sb, TypeShape t, List<TypeShape> siblings, int indent)
    {
        var pad = new string(' ', indent * 4);
        var emitted = false;
        foreach (var m in t.Members)
        {
            EmitMember(sb, m, indent, isInterface: true, typeName: t.Name);
            emitted = true;
        }
        if (!emitted)
        {
            // marker so an empty interface still compiles
            sb.Append(pad).AppendLine("// empty");
        }
    }

    private void EmitClassMembers(StringBuilder sb, TypeShape t, List<TypeShape> siblings, int indent)
    {
        var pad = new string(' ', indent * 4);
        var emitted = false;
        var ctorName = StripArity(t.Name);
        foreach (var m in t.Members)
        {
            EmitMember(sb, m, indent, isInterface: false, typeName: ctorName, typeIsAbstract: t.IsAbstract);
            emitted = true;
        }
        // Add stubs for the few BCL interfaces the manifest references
        // but the metadata walker didn't capture as explicit members
        // (because they're often explicit interface implementations or
        // inherited from System.ValueType / System.Object). Without
        // these, concrete types that implement IEquatable<T> etc. fail
        // the C# interface satisfaction check (CS0535).
        if (!t.IsAbstract)
        {
            EmitBclInterfaceStubs(sb, t, indent);
        }
        if (!emitted)
        {
            sb.Append(pad).AppendLine("// empty");
        }
    }

    private void EmitBclInterfaceStubs(StringBuilder sb, TypeShape t, int indent)
    {
        var pad = new string(' ', indent * 4);
        var hasEqualsT = t.Members.Any(m => m.Kind == "method" && m.Name == "Equals" && m.Parameters.Count == 1);
        var hasDispose = t.Members.Any(m => m.Kind == "method" && m.Name == "Dispose" && m.Parameters.Count == 0);
        var hasCompareToT = t.Members.Any(m => m.Kind == "method" && m.Name == "CompareTo" && m.Parameters.Count == 1);
        var hasIEquatable = t.Interfaces.Any(i => i.StartsWith("System.IEquatable", StringComparison.Ordinal));
        var hasIDisposable = t.Interfaces.Any(i => i == "System.IDisposable");
        var hasIComparable = t.Interfaces.Any(i => i.StartsWith("System.IComparable", StringComparison.Ordinal));
        if (hasIEquatable && !hasEqualsT)
        {
            // Extract the T from the interface name.
            var match = System.Text.RegularExpressions.Regex.Match(t.Interfaces.First(i => i.StartsWith("System.IEquatable", StringComparison.Ordinal)), @"IEquatable<(.+)>");
            var tName = match.Success ? match.Groups[1].Value : "object";
            sb.Append(pad).Append("public bool Equals(").Append(RefName(tName)).Append(" other) { return default!; }").AppendLine();
        }
        if (hasIDisposable && !hasDispose)
        {
            sb.Append(pad).AppendLine("public void Dispose() { }");
        }
        if (hasIComparable && !hasCompareToT)
        {
            var match = System.Text.RegularExpressions.Regex.Match(t.Interfaces.First(i => i.StartsWith("System.IComparable", StringComparison.Ordinal)), @"IComparable<(.+)>");
            var tName = match.Success ? match.Groups[1].Value : "object";
            sb.Append(pad).Append("public int CompareTo(").Append(RefName(tName)).Append(" other) { return default!; }").AppendLine();
        }
    }

    private static bool HasPointerType(MemberShape m)
    {
        if (m.ReturnType is not null && m.ReturnType.Contains('*')) return true;
        if (m.PropertyType is not null && m.PropertyType.Contains('*')) return true;
        if (m.FieldType is not null && m.FieldType.Contains('*')) return true;
        if (m.EventType is not null && m.EventType.Contains('*')) return true;
        foreach (var p in m.Parameters)
        {
            if (p.Type.Contains('*')) return true;
        }
        return false;
    }

    private void EmitMember(StringBuilder sb, MemberShape m, int indent, bool isInterface, string typeName = "", bool typeIsAbstract = false)
    {
        var pad = new string(' ', indent * 4);
        var access = m.IsPublic ? "public" : "protected";
        var modifiers = new List<string>();
        if (m.IsStatic) modifiers.Add("static");
        // Mark unsafe when the signature has pointer types.
        if (HasPointerType(m)) modifiers.Add("unsafe");
        if (!isInterface)
        {
            // Only emit `abstract` for abstract types. For concrete types,
            // the property/method is a real implementation regardless of
            // what the metadata's `IsAbstract` flag says (interface
            // implementations report IsAbstract=true).
            if (m.IsAbstract && typeIsAbstract) modifiers.Add("abstract");
        }
        var modStr = modifiers.Count > 0 ? " " + string.Join(" ", modifiers) : string.Empty;

        switch (m.Kind)
        {
            case "ctor":
                sb.Append(pad).Append(access).Append(modStr).Append(' ').Append(typeName).Append('(');
                sb.Append(string.Join(", ", m.Parameters.Select(FormatParam)));
                sb.AppendLine(") { }");
                break;
            case "method":
            {
                var genericParams = m.GenericParams.Count == 0
                    ? string.Empty
                    : $"<{string.Join(", ", m.GenericParams)}>";
                var constraints = new List<string>();
                foreach (var gc in m.GenericConstraints)
                {
                    var w = FormatWhereClause(gc);
                    if (w is not null) constraints.Add(w);
                }
                var constraintStr = constraints.Count > 0 ? " " + string.Join(" ", constraints) : string.Empty;
                var retType = RefName(m.ReturnType ?? "void");
                if (isInterface)
                {
                    sb.Append(pad).Append(modStr).Append(' ').Append(retType).Append(' ').Append(m.Name).Append(genericParams).Append('(');
                    sb.Append(string.Join(", ", m.Parameters.Select(FormatParam)));
                    sb.Append(')').Append(constraintStr).AppendLine(";");
                }
                else if (typeIsAbstract && m.IsAbstract)
                {
                    sb.Append(pad).Append("public").Append(modStr).Append(' ').Append(retType).Append(' ').Append(m.Name).Append(genericParams).Append('(');
                    sb.Append(string.Join(", ", m.Parameters.Select(FormatParam)));
                    sb.Append(')').Append(constraintStr).AppendLine(";");
                }
                else
                {
                    sb.Append(pad).Append("public").Append(modStr).Append(' ').Append(retType).Append(' ').Append(m.Name).Append(genericParams).Append('(');
                    sb.Append(string.Join(", ", m.Parameters.Select(FormatParam)));
                    sb.Append(')').Append(constraintStr).Append(' ').AppendLine(DefaultBody(retType));
                }
                break;
            }
            case "property":
            {
                var propType = m.PropertyType ?? "object";
                var accessors = new List<string>();
                if (m.PropertyCanRead) accessors.Add("get;");
                if (m.PropertyCanWrite) accessors.Add("set;");
                if (accessors.Count == 0) accessors.Add("get; set;");
                var hasIndexers = m.Parameters.Count > 0;
                // For interfaces, emit the property as a signature (no body).
                // For abstract classes with abstract members, emit as `abstract`.
                // For concrete classes (or non-abstract members), emit as expression-bodied.
                if (isInterface)
                {
                    if (hasIndexers)
                    {
                        sb.Append(pad).Append(RefName(propType)).Append(" this[").Append(string.Join(", ", m.Parameters.Select(FormatParam))).Append("] { ");
                        sb.Append(string.Join(" ", accessors));
                        sb.AppendLine(" }");
                    }
                    else
                    {
                        sb.Append(pad).Append(RefName(propType)).Append(' ').Append(m.Name).Append(" { ");
                        sb.Append(string.Join(" ", accessors));
                        sb.AppendLine(" }");
                    }
                }
                else if (typeIsAbstract && m.IsAbstract)
                {
                    sb.Append(pad).Append("public abstract ").Append(RefName(propType)).Append(' ').Append(m.Name);
                    if (hasIndexers)
                    {
                        sb.Append("[").Append(string.Join(", ", m.Parameters.Select(FormatParam))).Append("]");
                    }
                    sb.Append(" { ");
                    sb.Append(string.Join(" ", accessors));
                    sb.AppendLine(" }");
                }
                else
                {
                    // Concrete generated classes must retain BOTH getter and
                    // setter method tokens. The previous expression-bodied
                    // implementation silently discarded public setters, making
                    // real API-15 plugins fail with MissingMethodException (for
                    // example CommandInfo.set_HelpMessage).
                    if (hasIndexers)
                    {
                        sb.Append(pad).Append("public ").Append(RefName(propType)).Append(" this[").Append(string.Join(", ", m.Parameters.Select(FormatParam))).Append("] { ");
                    }
                    else
                    {
                        sb.Append(pad).Append("public ").Append(RefName(propType)).Append(' ').Append(m.Name).Append(" { ");
                    }
                    if (m.PropertyCanRead) sb.Append("get => ").Append(Line_DefaultValue(propType)).Append("; ");
                    if (m.PropertyCanWrite) sb.Append("set { } ");
                    if (!m.PropertyCanRead && !m.PropertyCanWrite) sb.Append("get => ").Append(Line_DefaultValue(propType)).Append("; ");
                    sb.AppendLine("}");
                }
                break;
            }
            case "field":
            {
                var rawFieldType = m.FieldType ?? "object";
                // Compiler-generated fixed-size-buffer types like
                // `FdtHeader+<Signature>e__FixedBuffer` aren't real types
                // we can re-emit; substitute a byte[] so the field has a
                // legal type.
                var fieldType = SanitizeFixedBufferType(RefName(rawFieldType));
                sb.Append(pad).Append(access).Append(modStr).Append(' ').Append(fieldType).Append(' ').Append(m.Name);
                if (m.IsStatic)
                {
                    sb.Append(" = ").Append(Line_DefaultValue(fieldType));
                }
                sb.AppendLine(";");
                break;
            }
            case "event":
            {
                var handler = m.EventType ?? "System.EventHandler";
                sb.Append(pad).Append(access).Append(modStr).Append(" event ").Append(RefName(handler)).Append(' ').Append(m.Name).AppendLine(";");
                break;
            }
        }
    }

    private static string UseDeclaringType(MemberShape m, string fallback)
    {
        return m.Name;
    }

    private string FormatParam(ParamShape p)
    {
        var t = RefName(p.Type);
        // `params` is `T[]` in C# but the metadata reports the element
        // type `T` with a ParamArray attribute. Append `[]` if missing.
        if (p.IsParams)
        {
            if (!t.EndsWith("[]", StringComparison.Ordinal)) t = t + "[]";
            t = $"params {t}";
        }
        // `in` is the C# shorthand for `ref readonly`; you can't combine
        // them. If the param is `in`, we don't need to add `ref`.
        if (p.IsIn) t = $"in {t}";
        else if (p.IsByRef) t = $"ref {t}";
        if (p.IsOut) t = $"out {t}";
        var s = $"{t} {SafeIdentifier(p.Name)}";
        if (p.HasDefault)
        {
            s += " = " + FormatDefaultValue(t, p.DefaultValue);
        }
        return s;
    }

    private static readonly HashSet<string> ReservedWords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while",
    };

    private static string SafeIdentifier(string s)
    {
        if (string.IsNullOrEmpty(s)) return "arg";
        if (ReservedWords.Contains(s)) return "@" + s;
        // Identifiers can't start with a digit.
        if (char.IsDigit(s[0])) return "_" + s;
        return s;
    }

    private static string FormatDefaultValue(string typeName, string? raw)
    {
        if (raw is null) return "default!";
        // Boolean: real DLLs emit "True" / "False" with capitals.
        if (raw.Equals("True", StringComparison.Ordinal)) return "true";
        if (raw.Equals("False", StringComparison.Ordinal)) return "false";
        // Pointer sentinel: real DLLs use * for "default pointer".
        if (raw == "*") return "default!";
        // Empty string: use safe defaults per type.
        if (raw.Length == 0)
        {
            if (typeName == "string") return "\"\"";
            if (typeName == "char") return "'\\0'";
            return "default!";
        }
        // The Inspector captures `RawDefaultValue` for some char/enum
        // parameters as a U+FFFE sentinel; detect it and fall back.
        if (raw[0] == '\uFFFE') return "default!";
        // For char, wrap the value in single quotes.
        if (typeName == "char")
        {
            return "'" + raw + "'";
        }
        // For string, wrap the value in double quotes (escape inner quotes).
        if (typeName == "string")
        {
            return "\"" + raw.Replace("\"", "\\\"") + "\"";
        }
        // For float/double, make sure the literal has a suffix.
        if (typeName == "float" && !raw.EndsWith("f", StringComparison.Ordinal) && !raw.EndsWith("d", StringComparison.Ordinal))
        {
            return raw + "f";
        }
        if (typeName == "decimal" && !raw.EndsWith("m", StringComparison.Ordinal))
        {
            return raw + "m";
        }
        // For numeric / enum defaults, the ToString() is fine as-is.
        return raw;
    }

    private string Line_DefaultValue(string typeName)
    {
        // Strip namespace and any generic / array adornments.
        var s = typeName;
        s = StripGenericArgs(s, out _);
        s = StripArray(s);
        s = s.Trim();
        if (s.StartsWith("ref ", StringComparison.Ordinal)) s = s.Substring(4);
        if (s.StartsWith("global::", StringComparison.Ordinal)) s = s.Substring("global::".Length);

        switch (s)
        {
            case "void": return "null!";
            case "object":
            case "string":
            case "System.String":
                return "null!";
            default:
                if (s.EndsWith("?")) return "null!";
                return "default!";
        }
    }

    private string DefaultBody(string returnType)
    {
        if (returnType == "void") return "{ }";
        var s = returnType;
        s = StripGenericArgs(s, out _);
        s = StripArray(s);
        s = s.Trim();
        if (s.StartsWith("ref ", StringComparison.Ordinal)) s = s.Substring(4);
        if (s.StartsWith("global::", StringComparison.Ordinal)) s = s.Substring("global::".Length);
        switch (s)
        {
            case "object":
            case "string":
            case "System.String":
                return "{ return null!; }";
        }
        if (s.EndsWith("?")) return "{ return null!; }";
        return "{ return default!; }";
    }

    private static string SanitizeFixedBufferType(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        // The compiler-generated fixed-buffer type markers have the form
        // `<Name>e__FixedBuffer` somewhere in the type name. Replace with
        // `byte[]` since that's the closest legal stand-in.
        if (s.Contains("e__FixedBuffer"))
        {
            return "byte[]";
        }
        return s;
    }

    private string RefName(string typeRef)
    {
        if (string.IsNullOrEmpty(typeRef)) return "object";
        var s = typeRef;
        s = StripGenericArgs(s, out _);
        s = StripArray(s);
        s = s.Trim();
        if (s.StartsWith("ref ", StringComparison.Ordinal)) s = s.Substring(4);
        if (s.StartsWith("global::", StringComparison.Ordinal)) s = s.Substring("global::".Length);

        switch (s)
        {
            case "void":
            case "Void":
            case "System.Void":
                return "void";
            case "object":
            case "System.Object":
                return "object";
            case "string":
            case "System.String":
                return "string";
            case "bool":
            case "System.Boolean":
                return "bool";
            case "byte":
            case "System.Byte":
                return "byte";
            case "sbyte":
            case "System.SByte":
                return "sbyte";
            case "short":
            case "System.Int16":
                return "short";
            case "ushort":
            case "System.UInt16":
                return "ushort";
            case "int":
            case "System.Int32":
                return "int";
            case "uint":
            case "System.UInt32":
                return "uint";
            case "long":
            case "System.Int64":
                return "long";
            case "ulong":
            case "System.UInt64":
                return "ulong";
            case "float":
            case "System.Single":
                return "float";
            case "double":
            case "System.Double":
                return "double";
            case "decimal":
            case "System.Decimal":
                return "decimal";
            case "char":
            case "System.Char":
                return "char";
            case "System.IntPtr":
                return "nint";
            case "System.UIntPtr":
                return "nuint";
        }

        // System.* / Microsoft.* — keep the full path; the generator adds
        // usings for the namespaces it sees, but the full path is always
        // a valid C# reference even without the using. C#'s namespace
        // lookup doesn't walk through `using System;` to find
        // sub-namespaces, so partial stripping breaks compilation.
        if (s.StartsWith("System.", StringComparison.Ordinal) || s.StartsWith("Microsoft.", StringComparison.Ordinal))
        {
            return SanitizeFixedBufferType(typeRef.Replace('+', '.'));
        }

        // For non-System types — these are presumed to be in the same
        // generated assembly. Emit the full namespace-qualified name.
        // Nested types: convert '+' to '.'.
        return typeRef.Replace('+', '.');
    }

    private sealed class TypeOrder : IComparer<TypeShape>
    {
        public static readonly TypeOrder Comparer = new();
        public int Compare(TypeShape? x, TypeShape? y)
        {
            if (x is null && y is null) return 0;
            if (x is null) return -1;
            if (y is null) return 1;
            // Enums first (simplest), then delegates, then interfaces, then classes, then structs
            int Rank(TypeShape t) => t.Kind switch
            {
                "enum" => 0,
                "delegate" => 1,
                "interface" => 2,
                "class" => 3,
                "struct" => 4,
                _ => 5,
            };
            var r = Rank(x).CompareTo(Rank(y));
            if (r != 0) return r;
            return string.CompareOrdinal(x.Name, y.Name);
        }
    }
}
