namespace Dalagab.Omega.RegressionTests;

internal static partial class RegressionCases
{
    internal static void TestPluginSecurityIntelligenceContract()
    {
        var sigmascope = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "sigmascope.py"));
        Contains(sigmascope, "SIGMASCOPE_VERSION = \"2.9.0\"", "Sigmascope version is explicit so stale evidence can be refreshed");
        Contains(sigmascope, "Only HTTPS downloads are scanned", "Sigmascope refuses insecure artifact transports");
        Contains(sigmascope, "MAX_ARTIFACT_BYTES", "artifact downloads are bounded");
        Contains(sigmascope, "MAX_ARTIFACT_BYTES = 256 * 1024 * 1024", "artifact download ceiling accommodates large production plugin packages while remaining bounded");
        Contains(sigmascope, "MAX_ARCHIVE_UNCOMPRESSED = 512 * 1024 * 1024", "archive expansion remains bounded above large production packages");
        Contains(sigmascope, "MAX_ARCHIVE_ENTRIES", "archive entry count is bounded");
        Contains(sigmascope, "MAX_ARCHIVE_ENTRIES = 16_384", "archive ceiling accommodates legitimate multi-thousand-entry plugin packages while remaining bounded");
        Contains(sigmascope, "many_metadata[\"files\"] == 3000", "hardening suite proves packages above the former 1,024-entry ceiling remain scannable");
        Contains(sigmascope, "safe_member_name", "archive paths are validated before content inspection");
        Contains(sigmascope, "never", "Sigmascope documents its no-execution trust boundary");
        Contains(sigmascope, "compound.network-execute", "compound network/process risk is surfaced");
        Contains(sigmascope, "sourceToBinaryVerified", "source inspection does not imply source-to-binary verification");
        Contains(sigmascope, "source_candidate_records(", "source scanning retains repository, artifact-origin, and Git-ref provenance instead of relying only on RepoUrl");
        Contains(sigmascope, "_source_ref_candidates", "source scanning prefers immutable exact-version refs before mutable branch heads");
        Contains(sigmascope, "artifactIdentity", "artifact manifests can supply the plugin version used for source-ref resolution");
        Contains(sigmascope, "propagate_source_provenance_by_artifact", "exact package mirrors can inherit a resolved original-source association without claiming reproducible build verification");
        Contains(sigmascope, "select_plugin_source_scope", "monorepo source scans are narrowed to the actual plugin build graph");
        Contains(sigmascope, "/git/trees/", "GitHub source retrieval enumerates immutable tree metadata instead of downloading repository archives");
        Contains(sigmascope, "/git/blobs/", "GitHub source retrieval fetches only selected immutable blobs");
        False(sigmascope.Contains("/zipball/", StringComparison.Ordinal), "Sigmascope must not download GitHub source archives");
        var publicGitSource = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "public_git_source.py"));
        Contains(publicGitSource, "--filter=blob:none", "generic public Git source retrieval uses strict blobless partial fetches");
        False(publicGitSource.Contains("\"clone\"", StringComparison.Ordinal), "generic public Git retrieval must not clone or checkout whole repositories");
        Contains(sigmascope, "repository-context-only", "unrelated repository projects remain context instead of becoming plugin security evidence");
        Contains(sigmascope, "contextProjects", "sibling server and tooling projects remain visible as non-critical repository context");
        Contains(sigmascope, "project_closure", "plugin source scope follows transitive project references instead of traversing the whole repository");
        Contains(sigmascope, "source_override_key(", "human-reviewed source overrides use stable plugin/source identities instead of SQLite row ids");
        Contains(sigmascope, "sources/source-overrides.json", "validated public-source overrides remain a repository-side Sigmascope input");
        Contains(sigmascope, "plugin_security_current", "Sigmascope persists the current result per exact catalog variant");
        Contains(sigmascope, "plugin_security_automation_capabilities", "Sigmascope persists structured character/menu automation evidence");
        Contains(sigmascope, "derive_automation_capabilities", "Sigmascope derives bounded user-facing automation classifications");
        Contains(sigmascope, "game.character.move", "character movement control is classified explicitly");
        Contains(sigmascope, "game.character.execute_action", "character action execution is classified explicitly");
        Contains(sigmascope, "game.ui.callback", "game UI/menu callback control is classified explicitly");
        Contains(sigmascope, "automation.via_ipc", "automation supplied indirectly through IPC is classified explicitly");
        Contains(sigmascope, "Preserve last-known-good intelligence", "transient revalidation failures do not erase the last completed scan");

        Contains(sigmascope, "omega.plugin-security.dependencies.v2", "dependency inventory has an explicit machine-readable schema");
        Contains(sigmascope, "plugin_security_dependencies", "dependency records are persisted separately from security findings");
        Contains(sigmascope, "plugin_security_imports", "namespace/import evidence is persisted");
        Contains(sigmascope, "plugin_security_permission_candidates", "import/dependency evidence maps to explicit permission candidates");
        Contains(sigmascope, "PackageReference", "NuGet package references are inventoried");
        Contains(sigmascope, "ProjectReference", "project references are inventoried");
        Contains(sigmascope, "packages.lock.json", "locked NuGet dependency versions are inventoried");
        Contains(sigmascope, "project.assets.json", "resolved NuGet dependency versions are inventoried when present");
        Contains(sigmascope, "GetIpcSubscriber", "Dalamud IPC consumers are inventoried");
        Contains(sigmascope, "GetIpcProvider", "Dalamud IPC providers are inventoried separately from consumers");
        Contains(sigmascope, "plugin_security_ipc_endpoints", "historical IPC provider/consumer observations are persisted per scan");
        Contains(sigmascope, "plugin_security_ipc_registry", "current IPC providers are registered by exact channel identity");
        Contains(sigmascope, "resolved-ipc-provider", "IPC consumers can resolve to the plugin that exposes the channel");
        Contains(sigmascope, "exact-ipc-channel-provider", "IPC provider links use the exact Dalamud registration string rather than plugin-name guessing");
        Contains(sigmascope, "infer_ipc_consumer_relationship", "IPC consumers receive conservative required/feature/optional/unknown relationship inference");
        Contains(sigmascope, "missing-required-ipc-provider", "high-confidence required IPC providers become explicit dependency issues when absent");
        Contains(sigmascope, "relationship_confidence", "IPC relationship confidence is retained in normalized dependency evidence");
        Contains(sigmascope, "relationship_evidence_json", "IPC relationship evidence remains available server-side");
        Contains(sigmascope, "RequiredPlugins", "required external Dalamud plugin dependencies are inventoried from manifests");
        Contains(sigmascope, "OptionalPlugins", "soft external Dalamud plugin dependencies are preserved from manifests");
        Contains(sigmascope, "requirement", "dependency rows preserve required/soft/optional/bundled semantics");
        Contains(sigmascope, "DllImport", "native library imports are inventoried");
        Contains(sigmascope, "bundledManagedAssemblies", "managed libraries bundled in plugin packages are inventoried");
        Contains(sigmascope, "bundledNativeLibraries", "native libraries bundled in plugin packages are inventoried");
        Contains(sigmascope, "projectDependencySha256", "dependency/project declarations receive a stable fingerprint");
        Contains(sigmascope, "permissionCandidates", "dependency-derived permissions remain candidates rather than confirmed call-path findings");
        Contains(sigmascope, "parse_managed_pe", "managed PE metadata is parsed without loading assemblies");
        Contains(sigmascope, "#Strings", "managed metadata string heap is parsed directly");
        Contains(sigmascope, "managed-assembly-reference", "AssemblyRef dependencies are inventoried with resolved versions");
        Contains(sigmascope, "member-reference", "managed TypeRef/MemberRef symbols are inventoried");
        Contains(sigmascope, "ImplMap", "managed P/Invoke metadata is inventoried from ImplMap");
        Contains(sigmascope, "plugin_security_managed_assemblies", "managed assembly parse summaries are persisted");
        Contains(sigmascope, "plugin_security_managed_symbols", "managed metadata symbols are persisted for later call/diff analysis");
        Contains(sigmascope, "process.execute", "high-confidence metadata references can strengthen permission candidates without claiming runtime execution");
        Contains(sigmascope, "_decode_cil_calls", "compiled CIL method bodies are decoded without loading assemblies");
        Contains(sigmascope, "callvirt", "CIL virtual method call sites are recorded");
        Contains(sigmascope, "newobj", "CIL object-construction call sites are supported");
        Contains(sigmascope, "ldftn", "CIL function-pointer targets are recorded");
        Contains(sigmascope, "sourceMethodToken", "call-site evidence retains the containing compiled method token");
        Contains(sigmascope, "targetNativeLibrary", "calls to local P/Invoke stubs resolve to native libraries");
        Contains(sigmascope, "plugin_security_managed_calls", "compiled call-site evidence is persisted separately from metadata references");
        Contains(sigmascope, "targetMethodToken", "local compiled calls retain the exact MethodDef target token for graph traversal");
        Contains(sigmascope, "plugin_security_managed_reachability", "bounded local method reachability is persisted separately from call-site evidence");
        Contains(sigmascope, "MAX_MANAGED_REACHABILITY_DEPTH", "local graph traversal is depth bounded for hostile artifacts");
        Contains(sigmascope, "callback-name", "probable event callbacks can seed explicitly-labeled heuristic roots");
        Contains(sigmascope, "VeryHigh", "compiled call-site evidence strengthens permission confidence without claiming runtime reachability");
        Contains(sigmascope, "but it still does not prove that a runtime branch actually", "reachability evidence preserves the static-analysis runtime boundary");
        Contains(sigmascope, "plugin_security_dependency_resolutions", "current dependency rows are cross-referenced to catalog plugins/components");
        Contains(sigmascope, "plugin_security_dependency_components", "shared package/assembly/native/IPC dependencies receive reusable component identities");
        Contains(sigmascope, "resolved-plugin", "exact catalog plugin dependencies are represented as resolved plugin edges");
        Contains(sigmascope, "external-unresolved", "unresolved external and soft plugin dependencies remain visible instead of being dropped");
        Contains(sigmascope, "internal-name", "plugin dependency resolution prefers exact InternalName matches");
        Contains(sigmascope, "nuget:", "NuGet dependencies receive normalized component keys for cross-plugin usage queries");
        Contains(sigmascope, "refresh_dependency_graph", "dependency graph can be refreshed when catalog contents change without rescanning artifacts");
        Contains(sigmascope, "current completed scans only", "graph projection avoids duplicating historical scans in current dependency usage counts");
        Contains(sigmascope, "version_requirement", "dependency rows preserve declared version constraints separately from observed versions");
        Contains(sigmascope, "resolved_version", "resolved dependency versions are stored separately from declarations");
        Contains(sigmascope, "version_satisfies", "NuGet/plugin version constraints are evaluated conservatively");
        Contains(sigmascope, "unparsed-constraint", "unknown version syntax is not treated as an incompatibility");
        Contains(sigmascope, "plugin_security_dependency_issues", "missing dependencies and compatibility issues are persisted as a current projection");
        Contains(sigmascope, "missing-required-plugin", "required catalog plugin dependencies that cannot be resolved are surfaced explicitly");
        Contains(sigmascope, "soft-plugin-unresolved", "soft dependency absence remains visible without being treated as a hard failure");
        Contains(sigmascope, "major-version-divergence", "shared components at different major versions are surfaced conservatively as divergence");
        Contains(sigmascope, "not by itself proof of a runtime conflict", "component version divergence is not overstated as a definite conflict");
        Contains(sigmascope, "plugin_security_dependency_advisory_matches", "optional advisory enrichment is stored separately from dependency evidence");
        Contains(sigmascope, "load_advisories", "advisories are supplied locally rather than fetched by hostile-artifact analysis");
        Contains(sigmascope, "--advisories", "Sigmascope exposes an optional advisory-document hook without making advisories mandatory");
        Contains(sigmascope, "plugin_security_scan_lineage", "successive completed scans retain immutable lineage to the previous current scan");
        Contains(sigmascope, "plugin_security_dependency_drift", "dependency and permission changes are persisted as historical drift events");
        Contains(sigmascope, "plugin_security_source_artifact_comparisons", "source declarations and compiled-artifact dependency observations are compared per scan");
        Contains(sigmascope, "artifact-and-source-changed", "drift events preserve whether binary and source both changed");
        Contains(sigmascope, "scanner-changed", "Sigmascope-only enrichment changes are distinguishable from plugin release changes");
        Contains(sigmascope, "dependency-added", "dependency additions are explicit historical events");
        Contains(sigmascope, "version-changed", "dependency version drift is explicit historical evidence");
        Contains(sigmascope, "permission-added", "new permission candidates are tracked between scans");
        Contains(sigmascope, "compared-not-verified", "source/artifact comparison never claims reproducible source-to-binary verification");
        Contains(sigmascope, "MAX_DRIFT_EVENTS_PER_SCAN", "drift generation is bounded for hostile or pathological inputs");
        Contains(sigmascope, "Exercise the real persistence path", "Sigmascope self-test covers the SQLite write path");
        Contains(sigmascope, "ValidatingRedirectHandler", "Sigmascope validates redirects before following them and strips cross-host authorization");
        Contains(sigmascope, "duplicate normalized path", "Sigmascope rejects ambiguous duplicate archive paths");
        Contains(sigmascope, "symbolic-link entry", "Sigmascope rejects ZIP symbolic-link entries even though archives are never extracted");
        Contains(sigmascope, "MAX_DEPENDENCY_RECORDS_PER_SCAN", "Sigmascope caps per-analysis dependency evidence");
        Contains(sigmascope, "_identityMaps", "Sigmascope uses ephemeral per-analysis identity maps instead of quadratic evidence deduplication");
        Contains(sigmascope, "droppedByCollection", "bounded evidence truncation is explicit rather than silent");
        Contains(sigmascope, "MAX_CURRENT_DEPENDENCY_ROWS", "Sigmascope bounds current graph materialization before loading it into memory");
        Contains(sigmascope, "MAX_ADVISORIES", "Sigmascope bounds advisory input size");
        Contains(sigmascope, "MAX_ADVISORY_MATCHES", "Sigmascope bounds advisory projection amplification");
        Contains(sigmascope, "platform-version-variation", "framework assembly version noise is retained without emitting false conflict issues");
        Contains(sigmascope, "validate_database_health", "Sigmascope performs integrity, foreign-key and projection-consistency validation");
        Contains(sigmascope, "SAVEPOINT omega_scan_persist", "each scan persistence write is rollback-safe");
        Contains(sigmascope, "--max-batch-seconds", "Sigmascope can stop starting examinations before the workflow wall-clock limit");
        Contains(sigmascope, "--hardening-self-test", "Sigmascope includes a deterministic catalog-scale/pathological-input stress fixture");
        Contains(sigmascope, "dependency_hardening_version", "Sigmascope marks catalogs that passed the hardening projection checks");

        var buildInfo = File.ReadAllText(Path.Combine(Root, "Omega", "BuildInfo.cs"));
        Contains(buildInfo, "BuildStamp = \"omega-", "production build stamp is release-oriented rather than internal-workflow oriented");
        Equal(2, buildInfo.Split("public const string", StringSplitOptions.None).Length - 1, "production build metadata contains only the release version and release stamp constants");
        False(buildInfo.Contains("repair", StringComparison.OrdinalIgnoreCase), "production build stamp does not expose repair labels");

        var workflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "sigmascope.yml"));
        var normalizedWorkflow = workflow.ReplaceLineEndings("\n");
        Contains(normalizedWorkflow, "name: Omega Sigmascope continuous worker", "Sigmascope is a continuous evidence worker rather than a client publisher");
        Contains(normalizedWorkflow, "cron: \"*/15 * * * *\"", "Sigmascope processes one bounded queue item every fifteen minutes");
        Contains(normalizedWorkflow, "ref: catalog-data", "Sigmascope consumes the current frozen canonical catalog/Definitions snapshot");
        Contains(normalizedWorkflow, "path: catalog/active-state", "frozen canonical state is isolated from the scanner checkout");
        Contains(normalizedWorkflow, "ref: security-evidence-v2", "Sigmascope begins from the last-known-good detailed evidence snapshot");
        Contains(normalizedWorkflow, "OMEGA_FROZEN_WORKER: catalog/active-state/definitions/worker", "Sigmascope executes the worker bundle published with frozen Definitions");
        False(normalizedWorkflow.Contains("git checkout --detach", StringComparison.Ordinal), "Sigmascope never depends on a historical development checkout");
        Contains(normalizedWorkflow, "Verify frozen worker bundle before execution", "frozen worker bytes are verified before any scanner code executes");
        Contains(normalizedWorkflow, "definitions_snapshot.py", "bundle-internal Definitions verification is executed from frozen catalog-data");
        Contains(normalizedWorkflow, "catalog_json_store.py", "worker materializes its relational scan input using frozen catalog tooling");
        Contains(normalizedWorkflow, "production_sigmascope_v2_pipeline.py", "Sigmascope analysis is staged through the production v2 orchestrator");
        Contains(normalizedWorkflow, "--skip-marketplace", "continuous worker cannot build or publish the Omega client database");
        Contains(normalizedWorkflow, "--frozen-advisories catalog/active-state/definitions/osv-advisories.json", "worker uses the day's frozen advisory universe");
        Contains(normalizedWorkflow, "--catalog-revision", "scan provenance records the exact canonical Catalog Revision");
        Contains(normalizedWorkflow, "--definitions-revision", "scan provenance records the exact frozen Definitions Revision");
        Contains(normalizedWorkflow, "--scanner-revision", "scan provenance records the exact frozen worker implementation revision");
        Contains(normalizedWorkflow, "--scanner-bundle-sha256", "scan provenance records the frozen worker manifest hash");
        Contains(normalizedWorkflow, "--artifact-analysis-revision", "artifact rescan identity is narrower than the complete frozen worker bundle");
        Contains(normalizedWorkflow, "--source-analysis-revision", "source rescan identity is narrower than the complete frozen worker bundle");
        False(normalizedWorkflow.Contains("--definitions-source-commit", StringComparison.Ordinal), "development commit provenance is not an execution dependency");
        Contains(normalizedWorkflow, "--rule-set-revision", "scan provenance records the scanner rule-set revision independently");
        Contains(normalizedWorkflow, "--queue-seed catalog/active-state/scan-queue.json", "production selection is owned by the immutable daily queue seed");
        Contains(normalizedWorkflow, "--max-scans 1", "each scheduled worker is bounded to one exact candidate");
        False(normalizedWorkflow.Contains("--rescan-after-hours", StringComparison.Ordinal), "production scheduling is event-driven rather than age/TTL driven");
        Contains(normalizedWorkflow, "contents: write", "final validated v2 snapshot publication has repository write permission");
        Contains(workflow, "publish_security_evidence_v2.py", "validated v2 publication is an explicit final step");
        Contains(workflow, "--snapshot-validation-report", "v2 push requires intrinsic snapshot validation");
        Contains(workflow, "--audit-report", "v2 push requires the independent developer audit");
        Contains(workflow, "production-sigmascope-v2-report.json", "each worker retains an auditable v2 production summary");
        False(workflow.Contains("workflow_run:", StringComparison.Ordinal), "continuous scanner is not coupled to every catalog run");
        False(workflow.Contains("gh release upload catalog-latest", StringComparison.Ordinal), "continuous scanner never publishes the client DB");
        False(workflow.Contains("validate_marketplace_catalog.py", StringComparison.Ordinal), "continuous scanner no longer builds a client projection");
        False(workflow.Contains("omega-marketplace.sqlite.zip", StringComparison.Ordinal), "continuous scanner never transports a client database");
        False(workflow.Contains("omega-security-evidence.sqlite.zip", StringComparison.Ordinal), "production Sigmascope no longer transports the giant v1 evidence SQLite database");

        var productionV2Pipeline = File.ReadAllText(Path.Combine(Root, "tools", "security", "production_sigmascope_v2_pipeline.py"));
        Contains(productionV2Pipeline, "frozen-definitions", "production worker distinguishes frozen Definitions coverage from live lookups");
        Contains(productionV2Pipeline, "notCoveredByFrozenDefinitions", "new dependency observations outside the daily OSV universe remain explicit");
        Contains(productionV2Pipeline, "scan_queue.select_next", "production scanner selects one item from persistent queue state under the workflow concurrency lock");
        Contains(productionV2Pipeline, "scan_queue.finish_attempt", "queue attempts are completed or backed off explicitly without leases");
        Contains(productionV2Pipeline, "queueSeedRevision", "evidence publication records the queue seed provenance");
        Contains(productionV2Pipeline, "primaryReason", "evidence publication records why the variant was scanned");
        Contains(productionV2Pipeline, "work_type == \"artifact\"", "artifact queue work forces source resolution off instead of coupling source availability to binary scanning");
        Contains(productionV2Pipeline, "scan_queue.enqueue_source_followup", "a completed artifact item schedules source resolution as a separate later work item");
        var scanQueue = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "scan_queue.py"));
        Contains(scanQueue, "\"workType\": \"artifact\"", "daily security queue identifies artifact work explicitly");
        Contains(scanQueue, "artifact-target-v2-", "artifact queue fingerprints are namespaced independently from source work");
        Contains(scanQueue, "artifact_analysis_revision", "artifact scheduling is driven by the narrow artifact-analysis revision");
        Contains(scanQueue, "\"workType\": \"source\"", "source resolution has its own typed queue work");
        Contains(scanQueue, "source-target-v2-", "source work has an independent target fingerprint namespace");
        Contains(scanQueue, "source_analysis_revision", "source scheduling is driven by the narrow source-analysis revision");
        Contains(scanQueue, "source_revision_changed", "default-branch source work is evented by observed immutable revision changes");
        Contains(scanQueue, "\"workType\": \"advisory\"", "advisory projection has its own typed queue work");
        Contains(scanQueue, "advisory-target-v1-", "advisory projection has an independent global fingerprint namespace");
        False(scanQueue.Contains("periodic_revalidation", StringComparison.Ordinal), "plugin age never creates security work");
        False(scanQueue.Contains("def lease_next", StringComparison.Ordinal), "single-worker queue contains no distributed lease selector");
        False(scanQueue.Contains("def finish_lease", StringComparison.Ordinal), "single-worker queue contains no lease completion API");
        Contains(scanQueue, "enqueue_source_followup", "artifact completion can enqueue an asynchronous source follow-up without reopening artifact work");
        False(scanQueue.Contains("reasons.append(\"source_review_due\")", StringComparison.Ordinal), "source review state cannot requeue artifact analysis");
        Contains(sigmascope, ".deps.json", "packaged .deps.json files are inspected for exact resolved NuGet package versions");
        var securityValidator = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "validate_security_catalog.py"));
        Contains(securityValidator, "plugin_security_dependencies", "validator checks dependency intelligence persistence");
        Contains(securityValidator, "plugin_security_permission_candidates", "validator checks permission candidate persistence");
        Contains(securityValidator, "plugin_security_managed_assemblies", "validator checks managed assembly metadata persistence");
        Contains(securityValidator, "plugin_security_managed_symbols", "validator checks managed symbol persistence");
        Contains(securityValidator, "plugin_security_managed_calls", "validator checks compiled IL call-site persistence");
        Contains(securityValidator, "plugin_security_managed_reachability", "validator checks bounded reachability persistence");
        Contains(securityValidator, "plugin_security_dependency_resolutions", "validator checks catalog cross-reference edges");
        Contains(securityValidator, "plugin_security_dependency_components", "validator checks shared dependency component aggregation");
        Contains(securityValidator, "plugin_security_ipc_endpoints", "validator requires persisted IPC endpoint observations");
        Contains(securityValidator, "plugin_security_ipc_registry", "validator requires the current IPC provider registry");
        Contains(securityValidator, "resolved IPC edges are missing provider registrations", "validator rejects IPC edges that cannot be backed by a registered provider");
        Contains(securityValidator, "plugin_security_dependency_issues", "validator checks version/missing dependency issue persistence");
        Contains(securityValidator, "plugin_security_dependency_advisory_matches", "validator checks advisory match projection");
        Contains(securityValidator, "plugin_security_scan_lineage", "validator checks scan lineage persistence");
        Contains(securityValidator, "plugin_security_dependency_drift", "validator checks historical dependency drift persistence");
        Contains(securityValidator, "plugin_security_source_artifact_comparisons", "validator checks source/artifact comparison persistence");
        Contains(securityValidator, "foreign_key_check", "validator refuses catalogs with foreign-key violations");
        Contains(securityValidator, "security_revision_candidate", "validator checks semantic security revision metadata");

        var builder = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "build_sqlite_catalog.py"));
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_scans", "catalog schema preserves Sigmascope analysis history in the legacy security scan table");
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_findings", "catalog schema stores individual findings");
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_current", "catalog schema stores current per-variant security state");
        Contains(builder, "CREATE TABLE IF NOT EXISTS manifest_observations", "catalog stores manifest publication observations separately from downloaded artifacts");
        Contains(builder, "CREATE TABLE IF NOT EXISTS source_repositories", "catalog stores canonical source repository identities separately from manifest feeds");
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_identity_aliases", "catalog stores normalized identity aliases without making any single alias authoritative");
        Contains(sigmascope, "CREATE TABLE IF NOT EXISTS artifact_blobs", "Sigmascope gives downloaded package bytes their own SHA-256 identity");
        Contains(sigmascope, "analysis_payload_json", "artifact analyses keep a reusable local payload while Evidence v2 transports normalized evidence");
        Contains(sigmascope, "clone-normalized-evidence", "later workers can reuse normalized Evidence v2 rows after proving the same artifact SHA-256");
        Contains(sigmascope, "artifactAnalysisReused", "artifact reuse is explicit in scanner results rather than silently skipping work");
        Contains(sigmascope, "def scan_source_row", "source-only work starts from completed artifact evidence instead of redownloading the plugin package");
        Contains(sigmascope, "analyze=False", "source resolution can establish repository/ref identity before source-body analysis");
        Contains(sigmascope, "sourceAnalysisReused", "source-analysis reuse is explicit and independently auditable");
        Contains(sigmascope, "CREATE TABLE IF NOT EXISTS source_revisions", "Sigmascope stores immutable source revisions separately from artifacts");
        Contains(sigmascope, "CREATE TABLE IF NOT EXISTS artifact_source_attributions", "artifact-to-source relationships carry explicit attribution evidence");
        Contains(sigmascope, "confidence IN (0,40,70,95,100)", "source attribution uses the machine confidence ladder rather than prose-only trust");
        Contains(builder, "security_status", "runtime catalog view exposes security state to Omega");
        Contains(builder, "catalog_base_revision", "catalog builder computes a stable semantic base revision");
        var revisions = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "catalog_revisions.py"));
        Contains(revisions, "omega.catalog-revision.v1", "catalog revision semantics have an explicit schema");
        Contains(revisions, "omega.security-revision.v2", "security revision semantics have an explicit schema");
        Contains(revisions, "omega.security-evidence-revision.v1", "detailed evidence revision semantics have an explicit schema");
        Contains(revisions, "CREATE TABLE IF NOT EXISTS catalog_changelog", "semantic catalog changes are persisted inside SQLite");
        Contains(revisions, "scan timestamps", "revision implementation explicitly excludes scan timestamps from semantic identity");
        Contains(revisions, "append_changelog_if_changed", "changelog rows are appended only for semantic catalog changes");

        var store = File.ReadAllText(Path.Combine(Root, "Omega", "Services", "SqliteCatalogStore.cs"));
        Contains(store, "SecurityArtifactSha256", "runtime reads exact scanned artifact hashes");
        Contains(store, "ReadSecurityFindings", "runtime reads structured security findings from SQLite");
        Contains(store, "catalog_revision", "runtime reads semantic Catalog Revision metadata");
        Contains(store, "security_revision", "runtime reads semantic Security Revision metadata");
        Contains(store, "evidence_revision", "runtime reads server-side Evidence Revision metadata without downloading evidence");
        Contains(store, "security_dependencies_json", "runtime reads the bounded dependency summary from Definitions");
        Contains(store, "ReadDependencies", "runtime deserializes structured dependency summaries");
        Contains(store, "SecuritySourceAttributionConfidence", "runtime reads source attribution strength independently of security severity");
        Contains(store, "SecurityReviewCoverageLabel", "runtime exposes review coverage as its own presentation dimension");
        var securityUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Sigmascope.cs"));
        Contains(securityUi, "Review: {coverage}", "product UI presents review coverage separately from security severity");
        Contains(securityUi, "not a probability", "attribution confidence is explicitly described as an ordinal evidence level");
        DoesNotContain(securityUi, "closed source", "source-unavailable evidence never infers developer intent as closed source");
        var dependencyModel = File.ReadAllText(Path.Combine(Root, "Omega", "Models", "MarketplaceDependency.cs"));
        Contains(dependencyModel, "TargetInternalName", "dependency summaries retain resolved Omega plugin targets");
        Contains(dependencyModel, "WarningSeverity", "dependency summaries retain warning/advisory severity without detailed evidence");

        var onlineClient = File.ReadAllText(Path.Combine(Root, "Omega", "Services", "OnlineCatalogClient.cs"));
        Contains(onlineClient, "CatalogRevision", "online descriptor carries Catalog Revision diagnostics");
        Contains(onlineClient, "SecurityRevision", "online descriptor carries Security Revision diagnostics");
        Contains(onlineClient, "EvidenceRevision", "online marketplace descriptor carries Evidence Revision diagnostics");
        Contains(onlineClient, "DatabaseRole", "online descriptor explicitly identifies the client marketplace database role");
        Contains(onlineClient, "DetailedSecurityEvidenceIncluded", "client rejects descriptors that attempt to ship detailed evidence");
        Contains(store, "database_role", "SQLite validation rejects a server-side evidence database while allowing legacy bootstrap catalogs");
        Contains(store, "runtimeColumns.Contains(\"security_automation_level\")", "older security-enriched catalogs remain readable before automation columns exist");
        False(onlineClient.Contains("security-evidence-latest", StringComparison.Ordinal), "Omega client contains no security-evidence release endpoint");
        False(onlineClient.Contains("omega-security-evidence.sqlite.zip", StringComparison.Ordinal), "Omega client cannot download the detailed evidence database");
        Contains(onlineClient, "64L * 1024 * 1024", "client transport ceiling accommodates compacted production catalogs while remaining bounded");

        var about = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Security.cs"));
        Contains(about, "About Omega", "version footer opens a dedicated About surface");
        Contains(about, "DrawAboutIdentityHero", "About gives the Omega identity its own visual hero");
        Contains(about, "var iconSize = Ui(112f)", "About presents the application icon at a useful size");
        Contains(about, "omegaIconTexture?.GetWrapOrDefault()", "About uses the packaged Omega application artwork");
        Contains(about, "Every plugin. One orbit.", "About leads with Omega's product tagline");
        Contains(about, "/omega   /omg", "About advertises both commands that open Omega");
        Contains(about, "Find more. Know more. Install with confidence.", "About sells the core discovery and trust workflow");
        Contains(about, "DrawAboutVersionAndDefinitions", "About presents the application version and Definitions as separate moving parts");
        DoesNotContain(about, "The installed Omega application release", "About keeps Version concise instead of explaining the obvious application version label");
        Contains(about, "Definitions also carry Omega's plugin listings, repositories, compatibility and dependency data.", "About keeps the Definitions explanation concise beneath Sigmascope");
        Contains(about, "omega-about-scrollable-body", "About keeps the identity and Definitions fixed while lower product/help content can scroll");
        Contains(about, "DrawAboutSigmascopeFeature", "About exposes Sigmascope as a first-class product capability");
        Contains(about, "sigmascopeBannerTexture?.GetWrapOrDefault()", "About uses the packaged Sigmascope banner artwork");
        Contains(about, "Sigmascope is Omega's online scanning engine", "About explains Sigmascope in player-facing language");
        Contains(about, "sends the results to Omega in Definitions packages", "About explains the Sigmascope-to-Definitions handoff");
        Contains(about, "ImGui.TextDisabled(\"Dalagab Group\")", "About keeps the publisher beneath the Omega name without duplicating the version");
        DoesNotContain(about, "Version {BuildInfo.Version} · Dalagab Group", "About does not duplicate the version inside the identity hero");
        DoesNotContain(about, "Discover the wider Dalamud plugin ecosystem", "About identity hero avoids redundant marketplace explanatory copy");
        DoesNotContain(about, "Omega's static evidence-gathering engine", "About avoids implementation-oriented Sigmascope copy for ordinary players");
        Contains(about, "var leftInset = Ui(12f)", "About identity hero is aligned toward the content edge with scale-aware inset instead of being centered in the modal");
        Contains(about, "DrawAboutWrappedBullet", "About wraps long lower-section bullet copy instead of allowing horizontal clipping");
        Contains(about, "catalog.DefinitionsRevision", "About shows the actual frozen Definitions revision when available");
        Contains(about, "catalog.CatalogRevision", "About can fall back to the Catalog Revision for older databases without Definitions metadata");
        DoesNotContain(about, "Security Revision", "About does not expose internal security revision identity");
        DoesNotContain(about, "Evidence Revision", "About does not expose server-side evidence identity");
        DoesNotContain(about, "Definitions changelog entries", "About does not expose internal changelog counts");

        var product = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Sigmascope.cs"));
        Contains(product, "Observed capabilities", "product page explains observed permissions/capabilities");
        Contains(product, "Detailed findings", "product page exposes expandable detailed findings");
        Contains(product, "No findings is not proof", "product page avoids claiming that static analysis proves safety");
        Contains(product, "The published package was not verified to match that source.", "product page preserves source provenance uncertainty");
        Contains(product, "SecurityAutomationCapabilities.Count > 0", "product page renders structured character/menu automation evidence when present");
        Contains(product, "ImGui.TextUnformatted(\"Automation\")", "product page labels the structured automation section clearly");
        Contains(product, "AutomationLevelLabel(plugin.SecurityAutomationLevel)", "product page renders the normalized automation classification");
        Contains(product, "Full gameplay automation", "product page can distinguish the strongest automation class");
        DoesNotContain(product, "Highest:", "product hero severity badge uses a concise risk label");
        Contains(product, "\"high\" => new SigmascopeVisual", "high severity has an explicit shared card/product visual");
        Contains(product, "\"caution\" or \"medium\" => new SigmascopeVisual", "caution severity is presented through the shared Medium visual");
        Contains(product, "\"informational\" or \"low\" => new SigmascopeVisual", "informational severity is presented through the shared Low visual");
        Contains(product, "\"No findings\"", "completed no-finding scans use the same user-facing label on cards and product pages");
        Contains(product, "Analyzed {scanned.ToLocalTime():g}", "Sigmascope analysis timestamp is retained in the detailed evidence section");
        Contains(product, "Findings:", "detailed security section retains severity counts away from the hero");
        Contains(product, "DrawSecurityBulletList", "observed capabilities render as readable vertical bullets instead of one dense line");
        var dependenciesUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Dependencies.cs"));
        Contains(dependenciesUi, "Dependencies", "product page exposes a dedicated dependency section");
        Contains(dependenciesUi, "DrawDependencyEmptyState", "dependency section stays visible even when a package has no projected dependency rows");
        Contains(dependenciesUi, "No external plugin or IPC dependencies were detected for this package.", "completed scans explain a genuine zero plugin-dependency result");
        Contains(dependenciesUi, "Dependency information is not present in the current Definitions snapshot for this package.", "older or unscanned Definitions snapshots explain missing dependency data instead of hiding the view");
        DoesNotContain(dependenciesUi, "if (!plugin.HasCompletedSecurityScan || plugin.SecurityDependencyTotalCount <= 0 || plugin.SecurityDependencies.Count == 0)", "dependency section must not disappear behind the old security/dependency guard");
        Contains(dependenciesUi, "Available in Omega", "resolved plugin dependencies advertise that they can be opened in Omega");
        Contains(dependenciesUi, "Provided by {dependency.TargetInternalName}", "resolved IPC consumers name the plugin that provides the channel");
        Contains(dependenciesUi, "Required plugins / providers", "required IPC providers are presented alongside required plugin dependencies");
        Contains(dependenciesUi, "Feature integrations", "feature-scoped IPC relationships receive their own dependency group");
        Contains(dependenciesUi, "IsHighConfidenceRequiredProvider", "required-provider warnings are limited to strong relationship evidence");
        Contains(dependenciesUi, "RelationshipReason", "bounded relationship evidence is explainable from the dependency UI");
        Contains(dependenciesUi, "Multiple IPC providers observed", "ambiguous IPC provider registrations remain explicit instead of being guessed");
        Contains(dependenciesUi, "OpenPluginDetails", "resolved plugin dependencies navigate to their Omega product page");
        Contains(dependenciesUi, "IsDisplayablePluginDependency", "dependency UI filters legacy Definitions rows to plugin and IPC relationships");
        Contains(dependenciesUi, "dependency.IsFramework", "framework dependencies are explicitly excluded from the product dependency panel");
        DoesNotContain(dependenciesUi, "Provided by framework", "framework components are not presented as plugin dependencies");
        DoesNotContain(dependenciesUi, "Bundled / observed", "implementation components do not get a dependency group");
        var productPage = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.ProductPage.cs"));
        Contains(productPage, "DrawProductDependencies(plugin, installed)", "product page always includes the dependency view");
        True(
            productPage.IndexOf("DrawProductDependencies(plugin, installed)", StringComparison.Ordinal) <
            productPage.IndexOf("DrawProductSourcePackages(plugin, sourcePackages, currentApi, currentDalamudVersion)", StringComparison.Ordinal),
            "Dependencies render before package provenance so the dependency view is not buried below package details");

        var packagesUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.SourcePackages.cs"));
        Contains(packagesUi, "Packages & repositories", "product page explains distinct downloadable source packages");
        Contains(packagesUi, "SecurityArtifactSha256", "scanned package hashes collapse repository mirrors that point at the same artifact");
        Contains(packagesUi, "Repository manifests pointing to this package", "each package lists the repository manifests that reference it");
        DoesNotContain(packagesUi, "$\"Packages {packages.Count}  •  Repository manifests {manifestCount}\"", "package/repository totals are not repeated above the package rows");
        DoesNotContain(packagesUi, "ImGuiTreeNodeFlags.DefaultOpen", "package entries are collapsed by default");
        Contains(packagesUi, "API: {package.ApiLevel}", "package API metadata is shown inside the expanded artifact metadata area");
        Contains(packagesUi, "FontAwesomeIcon.Flask", "testing-only packages use a testing icon rather than a text channel label");
        Contains(packagesUi, "headerMax.X - glyphSize.X - 10f", "testing icon is right-aligned inside the package row rather than overlapping label text");
        Contains(packagesUi, "package.IsTestingOnly", "testing-only package presentation is explicit");
        Contains(packagesUi, "0.23f, 0.20f, 0.07f", "testing-only package headers receive a subtle yellow background");
        Contains(packagesUi, "else if (preferredInstall)", "only the preferred install package receives the green installable treatment");
        Contains(packagesUi, "0.07f, 0.24f, 0.13f", "preferred install package uses the green header treatment");
        Contains(packagesUi, "0.08f, 0.09f, 0.11f", "non-installable historical packages use neutral headers");
        DoesNotContain(packagesUi, "package.Channels", "package headers do not expose Stable or Testing wording");
        Contains(packagesUi, "RepositoryProviderRules.SortPriority", "repository references follow shared preferred-provider ordering");
        Contains(packagesUi, "baselineDeviation", "same-version packages with a different artifact hash are marked against the green baseline");
        Contains(packagesUi, "0.30f, 0.07f, 0.08f", "artifact deviations receive the red package-header treatment");
        Contains(packagesUi, "Plugin differs from the preferred package baseline", "package divergence uses plugin terminology in the user-facing warning");
        Contains(packagesUi, "product-package-baseline-warning", "package divergence is promoted to a red warning panel at the top of the product page");
        Contains(packagesUi, "FontAwesomeIcon.ExclamationTriangle", "the promoted package divergence warning uses an exclamation icon");
        Contains(packagesUi, "Plugin package SHA-256", "package identity metadata avoids user-facing artifact terminology");
        var sourceComparisonUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.SourceSecurityComparison.cs"));
        Contains(sourceComparisonUi, "sameKnownArtifact", "source comparison uses exact artifact SHA identity before comparing reports");
        Contains(sourceComparisonUi, "Definitions integrity anomaly", "identical artifact hashes with different security results are treated as a data integrity fault");
        Contains(sourceComparisonUi, "Package differs from the preferred baseline", "different artifact hashes are explicitly compared against the green package baseline");
        var productPageSource = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.ProductPage.cs"));
        Contains(productPageSource, "ResolveProductBaselineVariant", "product metadata and security are anchored to the green preferred package");
        var projector = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "project_marketplace_catalog.py"));
        Contains(projector, "backfill_marketplace_security_from_completed_scans", "client projection recovers completed artifact scans even when a duplicate per-variant current pointer is missing");
        Contains(projector, "plugin_security_scans", "artifact security recovery uses immutable completed scan history as its authority");
        Contains(projector, "_normalized_package_url", "exact mirrored package URLs can reuse a proven artifact identity for the same plugin version");
        Contains(projector, "canonicalize_marketplace_security_by_artifact", "client security summaries are canonicalized by exact artifact hash");
        Contains(projector, "validate_artifact_security_consistency", "projection fails if identical artifact hashes retain different security summaries");
        Contains(projector, "build_advisory_risk_summaries", "known dependency advisories are summarized into the client security posture");
        Contains(projector, "adv.affected_version", "known-risk projection is scoped to the exact affected dependency version");
        Contains(projector, "security_risk_score", "the compact Definitions database carries Omega's bounded internal risk score");
        Contains(projector, "advisory_points", "known advisories explicitly add weight to the internal risk score");
        Contains(projector, "Canonicalize only artifact-intrinsic static conclusions", "artifact canonicalization does not overwrite repository-specific dependency/advisory projections");
        Contains(projector, "advisory_summaries.get(variant_id", "risk is recomputed per repository variant after static artifact canonicalization");
        Contains(projector, "relationshipConfidence", "Definitions project bounded IPC relationship confidence");
        Contains(projector, "relationshipReason", "Definitions project a bounded IPC relationship explanation without forensic evidence tables");

        var discoverUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Discover.cs"));
        var installUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Install.cs"));
        Contains(installUi, "Required provider not installed", "install chooser warns when a high-confidence required IPC provider is missing");
        Contains(installUi, "View provider", "install warning can route the user to a resolved required provider");
        Contains(installUi, "will not install it automatically", "inferred IPC dependencies remain assisted rather than silently installed");
        Contains(discoverUi, "FindRequiredDependencyAutomation", "automation resolver follows required plugin dependencies for automation exposure");
        Contains(discoverUi, "Automation exposure through required dependency", "dependency-provided automation is explained in the automation tooltip");
        Contains(discoverUi, "maximumDependencyRiskDepth = 8", "recursive dependency-automation traversal remains bounded");
        Contains(discoverUi, "plugin.SecurityDependencies", "dependency automation follows evidence from the exact selected repository package");
        Contains(securityUi, "FontAwesomeIcon.ExclamationTriangle", "scan findings use the standard Font Awesome warning-triangle glyph");
        Contains(securityUi, "Known risk", "product security surfaces a dedicated known-risk badge for OSV-affected dependencies");
        Contains(securityUi, "HasKnownAtRiskDependency", "known dependency advisories are handled independently from static findings");
        Contains(discoverUi, "Known risk: OSV reports", "Discover exposes a visible known-risk marker without revealing the numeric score");
        Contains(discoverUi, "UiBuilder.IconFontFixedWidth", "scan glyphs use Dalamud's fixed-width Font Awesome font for stable alignment");
        Contains(discoverUi, "var glyphSize = ImGui.CalcTextSize(glyph)", "scan glyph centering is derived from measured glyph bounds");
        Contains(discoverUi, "(size - glyphSize.X) * 0.5f", "scan glyphs remain horizontally centered without punctuation-specific offsets");
        Contains(discoverUi, "(size - glyphSize.Y) * 0.5f", "scan glyphs remain vertically centered without punctuation-specific offsets");
        DoesNotContain(discoverUi, "DrawPluginWarningTriangle", "the obsolete hand-drawn warning triangle renderer must not return");
    }
    internal static void TestCatalogCompactionWorkflowContract()
    {
        var compactor = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "compact_sqlite_catalog.py"));
        Contains(compactor, "COMPACTOR_VERSION = \"1.2.0\"", "database compactor version is explicit");
        Contains(compactor, "omega.plugin-security.scan-summary.v1", "redundant scan JSON is converted to a bounded summary schema");
        Contains(compactor, "runtime_projection_digest", "compactor hashes the complete runtime projection before and after rewriting");
        Contains(compactor, "preserved_counts", "compactor verifies historical and normalized evidence row counts are preserved");
        Contains(compactor, "VACUUM INTO", "compactor writes a fresh SQLite database instead of leaving free pages behind");
        Contains(compactor, "MAX_SUMMARY_BYTES = 64 * 1024", "historical summary payloads remain bounded");
        Contains(compactor, "plugin_security_managed_calls", "managed IL call evidence remains preserved during compaction");
        Contains(compactor, "plugin_security_dependency_drift", "historical dependency drift remains preserved during compaction");
        Contains(compactor, "--self-test", "compactor includes an isolated history-preservation regression fixture");
        Contains(compactor, "append_changelog_if_changed", "compactor finalizes semantic revisions and changelog before publication");
        Contains(compactor, "publication_required", "compactor records a semantic publication decision");
        Contains(compactor, "catalogRevision", "compactor writes the catalog revision into the production descriptor");
        Contains(compactor, "securityRevision", "compactor writes the security revision into the production descriptor");
        Contains(compactor, "changelogEntryCount", "descriptor exposes embedded changelog size for troubleshooting");
        var projector = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "project_marketplace_catalog.py"));
        Contains(projector, "PROJECTOR_VERSION = \"1.5.0\"", "marketplace projector version is explicit");
        Contains(projector, "marketplace_security_current", "client database retains only compact current security summaries");
        Contains(projector, "DEPENDENCY_SUMMARY_LIMIT = 30", "Definitions dependency projection remains bounded per plugin variant");
        Contains(projector, "build_dependency_summaries", "projector derives compact dependencies from detailed server-side evidence before dropping it");
        Contains(projector, "dependencies_json", "compact dependency summaries survive in the marketplace security projection");
        Contains(projector, "dependency_total_count", "Definitions retains the full dependency count when the displayed summary is truncated");
        Contains(projector, "DROP TABLE", "projector physically removes detailed security tables from the client database");
        Contains(projector, "detailedSecurityEvidenceIncluded", "marketplace descriptor explicitly excludes detailed security evidence");


        var workflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "catalog-compaction.yml"));
        Contains(workflow, "Omega legacy SQLite catalog compactor (disabled)", "v1 compactor is retained only as a manual compatibility tool");
        Contains(workflow, "workflow_dispatch:", "legacy compactor can be invoked manually for compatibility testing");
        False(workflow.Contains("workflow_run:", StringComparison.Ordinal), "legacy compactor is removed from the production chain");
        False(workflow.Contains("gh release upload", StringComparison.Ordinal), "legacy compactor cannot publish production data");
        Contains(workflow, "compact_sqlite_catalog.py --self-test", "legacy compactor implementation remains regression tested");
        Contains(compactor, "validate_compacted_database", "legacy compactor still validates its compacted evidence database");

        var sigmascopeWorkflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "sigmascope.yml"));
        Contains(sigmascopeWorkflow, "Publish validated Security Evidence v2 snapshot atomically", "production Sigmascope publishes detailed v2 evidence only after validation and audit");
        Contains(sigmascopeWorkflow, "security-developer-audit.json", "independent conclusion audit remains an evidence publication gate");
        Contains(sigmascopeWorkflow, "--skip-marketplace", "continuous evidence workers cannot publish client Definitions");
        False(sigmascopeWorkflow.Contains("omega-marketplace.sqlite.zip", StringComparison.Ordinal), "continuous evidence workers do not transport the client database");
        False(sigmascopeWorkflow.Contains("gh release upload catalog-latest", StringComparison.Ordinal), "continuous evidence workers cannot replace the client database");
        False(sigmascopeWorkflow.Contains("omega-security-evidence.sqlite.zip", StringComparison.Ordinal), "production chain no longer transports detailed evidence through a giant SQLite bundle");

        var dailyCatalogWorkflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "catalog-builder.yml"));
        Contains(dailyCatalogWorkflow, "compile_marketplace_snapshot.py", "daily compiler projects canonical JSON plus current evidence into the bounded client database");
        Contains(dailyCatalogWorkflow, "validate_marketplace_catalog.py --root catalog/client-dist", "daily client projection is validated before publication");
        Contains(dailyCatalogWorkflow, "gh release upload catalog-latest", "client Definitions publication occurs only at the daily/manual boundary");
        Contains(dailyCatalogWorkflow, "omega-marketplace.sqlite.zip", "client release continues to use the small marketplace bundle");
        var compactValidator = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "validate_compacted_catalog.py"));
        Contains(compactValidator, "foreign_key_check", "compaction validator refuses foreign-key violations");
        Contains(compactValidator, "catalog_changelog", "compaction validator requires the embedded changelog");
        Contains(compactValidator, "catalogRevision", "compaction validator checks descriptor/database revision identity");
    }

}
