namespace Dalagab.Omega.RegressionTests;

internal static partial class RegressionCases
{
    internal static void TestPluginSecurityIntelligenceContract()
    {
        var scanner = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "security_scan.py"));
        Contains(scanner, "SCANNER_VERSION = \"2.0.0\"", "scanner version is explicit so stale scans can be refreshed");
        Contains(scanner, "Only HTTPS downloads are scanned", "scanner refuses insecure artifact transports");
        Contains(scanner, "MAX_ARTIFACT_BYTES", "artifact downloads are bounded");
        Contains(scanner, "MAX_ARTIFACT_BYTES = 256 * 1024 * 1024", "artifact download ceiling accommodates large production plugin packages while remaining bounded");
        Contains(scanner, "MAX_ARCHIVE_UNCOMPRESSED = 512 * 1024 * 1024", "archive expansion remains bounded above large production packages");
        Contains(scanner, "MAX_ARCHIVE_ENTRIES", "archive entry count is bounded");
        Contains(scanner, "MAX_ARCHIVE_ENTRIES = 16_384", "archive ceiling accommodates legitimate multi-thousand-entry plugin packages while remaining bounded");
        Contains(scanner, "many_metadata[\"files\"] == 3000", "hardening suite proves packages above the former 1,024-entry ceiling remain scannable");
        Contains(scanner, "safe_member_name", "archive paths are validated before content inspection");
        Contains(scanner, "never", "scanner documents its no-execution trust boundary");
        Contains(scanner, "compound.network-execute", "compound network/process risk is surfaced");
        Contains(scanner, "sourceToBinaryVerified", "source inspection does not imply source-to-binary verification");
        Contains(scanner, "plugin_security_current", "scanner persists the current result per exact catalog variant");
        Contains(scanner, "plugin_security_automation_capabilities", "scanner persists structured character/menu automation evidence");
        Contains(scanner, "derive_automation_capabilities", "scanner derives bounded user-facing automation classifications");
        Contains(scanner, "game.character.move", "character movement control is classified explicitly");
        Contains(scanner, "game.character.execute_action", "character action execution is classified explicitly");
        Contains(scanner, "game.ui.callback", "game UI/menu callback control is classified explicitly");
        Contains(scanner, "automation.via_ipc", "automation supplied indirectly through IPC is classified explicitly");
        Contains(scanner, "Preserve last-known-good intelligence", "transient revalidation failures do not erase the last completed scan");

        Contains(scanner, "omega.plugin-security.dependencies.v1", "dependency inventory has an explicit machine-readable schema");
        Contains(scanner, "plugin_security_dependencies", "dependency records are persisted separately from security findings");
        Contains(scanner, "plugin_security_imports", "namespace/import evidence is persisted");
        Contains(scanner, "plugin_security_permission_candidates", "import/dependency evidence maps to explicit permission candidates");
        Contains(scanner, "PackageReference", "NuGet package references are inventoried");
        Contains(scanner, "ProjectReference", "project references are inventoried");
        Contains(scanner, "packages.lock.json", "locked NuGet dependency versions are inventoried");
        Contains(scanner, "project.assets.json", "resolved NuGet dependency versions are inventoried when present");
        Contains(scanner, "GetIpcSubscriber", "Dalamud IPC integrations are inventoried");
        Contains(scanner, "RequiredPlugins", "required external Dalamud plugin dependencies are inventoried from manifests");
        Contains(scanner, "OptionalPlugins", "soft external Dalamud plugin dependencies are preserved from manifests");
        Contains(scanner, "requirement", "dependency rows preserve required/soft/optional/bundled semantics");
        Contains(scanner, "DllImport", "native library imports are inventoried");
        Contains(scanner, "bundledManagedAssemblies", "managed libraries bundled in plugin packages are inventoried");
        Contains(scanner, "bundledNativeLibraries", "native libraries bundled in plugin packages are inventoried");
        Contains(scanner, "projectDependencySha256", "dependency/project declarations receive a stable fingerprint");
        Contains(scanner, "permissionCandidates", "dependency-stage permissions remain candidates rather than confirmed call-path findings");
        Contains(scanner, "parse_managed_pe", "managed PE metadata is parsed without loading assemblies");
        Contains(scanner, "#Strings", "managed metadata string heap is parsed directly");
        Contains(scanner, "managed-assembly-reference", "AssemblyRef dependencies are inventoried with resolved versions");
        Contains(scanner, "member-reference", "managed TypeRef/MemberRef symbols are inventoried");
        Contains(scanner, "ImplMap", "managed P/Invoke metadata is inventoried from ImplMap");
        Contains(scanner, "plugin_security_managed_assemblies", "managed assembly parse summaries are persisted");
        Contains(scanner, "plugin_security_managed_symbols", "managed metadata symbols are persisted for later call/diff analysis");
        Contains(scanner, "process.execute", "high-confidence metadata references can strengthen permission candidates without claiming runtime execution");
        Contains(scanner, "_decode_cil_calls", "compiled CIL method bodies are decoded without loading assemblies");
        Contains(scanner, "callvirt", "CIL virtual method call sites are recorded");
        Contains(scanner, "newobj", "CIL object-construction call sites are supported");
        Contains(scanner, "ldftn", "CIL function-pointer targets are recorded");
        Contains(scanner, "sourceMethodToken", "call-site evidence retains the containing compiled method token");
        Contains(scanner, "targetNativeLibrary", "calls to local P/Invoke stubs resolve to native libraries");
        Contains(scanner, "plugin_security_managed_calls", "compiled call-site evidence is persisted separately from metadata references");
        Contains(scanner, "targetMethodToken", "local compiled calls retain the exact MethodDef target token for graph traversal");
        Contains(scanner, "plugin_security_managed_reachability", "bounded local method reachability is persisted separately from call-site evidence");
        Contains(scanner, "MAX_MANAGED_REACHABILITY_DEPTH", "local graph traversal is depth bounded for hostile artifacts");
        Contains(scanner, "callback-name", "probable event callbacks can seed explicitly-labeled heuristic roots");
        Contains(scanner, "VeryHigh", "compiled call-site evidence strengthens permission confidence without claiming runtime reachability");
        Contains(scanner, "but it still does not prove that a runtime branch actually", "reachability evidence preserves the static-analysis runtime boundary");
        Contains(scanner, "plugin_security_dependency_resolutions", "current dependency rows are cross-referenced to catalog plugins/components");
        Contains(scanner, "plugin_security_dependency_components", "shared package/assembly/native/IPC dependencies receive reusable component identities");
        Contains(scanner, "resolved-plugin", "exact catalog plugin dependencies are represented as resolved plugin edges");
        Contains(scanner, "external-unresolved", "unresolved external and soft plugin dependencies remain visible instead of being dropped");
        Contains(scanner, "internal-name", "plugin dependency resolution prefers exact InternalName matches");
        Contains(scanner, "nuget:", "NuGet dependencies receive normalized component keys for cross-plugin usage queries");
        Contains(scanner, "refresh_dependency_graph", "dependency graph can be refreshed when catalog contents change without rescanning artifacts");
        Contains(scanner, "current completed scans only", "graph projection avoids duplicating historical scans in current dependency usage counts");
        Contains(scanner, "version_requirement", "dependency rows preserve declared version constraints separately from observed versions");
        Contains(scanner, "resolved_version", "resolved dependency versions are stored separately from declarations");
        Contains(scanner, "version_satisfies", "NuGet/plugin version constraints are evaluated conservatively");
        Contains(scanner, "unparsed-constraint", "unknown version syntax is not treated as an incompatibility");
        Contains(scanner, "plugin_security_dependency_issues", "missing dependencies and compatibility issues are persisted as a current projection");
        Contains(scanner, "missing-required-plugin", "required catalog plugin dependencies that cannot be resolved are surfaced explicitly");
        Contains(scanner, "soft-plugin-unresolved", "soft dependency absence remains visible without being treated as a hard failure");
        Contains(scanner, "major-version-divergence", "shared components at different major versions are surfaced conservatively as divergence");
        Contains(scanner, "not by itself proof of a runtime conflict", "component version divergence is not overstated as a definite conflict");
        Contains(scanner, "plugin_security_dependency_advisory_matches", "optional advisory enrichment is stored separately from dependency evidence");
        Contains(scanner, "load_advisories", "advisories are supplied locally rather than fetched by hostile-artifact analysis");
        Contains(scanner, "--advisories", "scanner exposes an optional advisory-document hook without making advisories mandatory");
        Contains(scanner, "plugin_security_scan_lineage", "successive completed scans retain immutable lineage to the previous current scan");
        Contains(scanner, "plugin_security_dependency_drift", "dependency and permission changes are persisted as historical drift events");
        Contains(scanner, "plugin_security_source_artifact_comparisons", "source declarations and compiled-artifact dependency observations are compared per scan");
        Contains(scanner, "artifact-and-source-changed", "drift events preserve whether binary and source both changed");
        Contains(scanner, "scanner-changed", "scanner-only enrichment changes are distinguishable from plugin release changes");
        Contains(scanner, "dependency-added", "dependency additions are explicit historical events");
        Contains(scanner, "version-changed", "dependency version drift is explicit historical evidence");
        Contains(scanner, "permission-added", "new permission candidates are tracked between scans");
        Contains(scanner, "compared-not-verified", "source/artifact comparison never claims reproducible source-to-binary verification");
        Contains(scanner, "MAX_DRIFT_EVENTS_PER_SCAN", "drift generation is bounded for hostile or pathological inputs");
        Contains(scanner, "Exercise the real persistence path", "scanner self-test covers the SQLite write path");
        Contains(scanner, "ValidatingRedirectHandler", "scanner validates redirects before following them and strips cross-host authorization");
        Contains(scanner, "duplicate normalized path", "scanner rejects ambiguous duplicate archive paths");
        Contains(scanner, "symbolic-link entry", "scanner rejects ZIP symbolic-link entries even though archives are never extracted");
        Contains(scanner, "MAX_DEPENDENCY_RECORDS_PER_SCAN", "scanner caps per-scan dependency evidence");
        Contains(scanner, "_identityMaps", "scanner uses ephemeral per-scan identity maps instead of quadratic evidence deduplication");
        Contains(scanner, "droppedByCollection", "bounded evidence truncation is explicit rather than silent");
        Contains(scanner, "MAX_CURRENT_DEPENDENCY_ROWS", "scanner bounds current graph materialization before loading it into memory");
        Contains(scanner, "MAX_ADVISORIES", "scanner bounds advisory input size");
        Contains(scanner, "MAX_ADVISORY_MATCHES", "scanner bounds advisory projection amplification");
        Contains(scanner, "platform-version-variation", "framework assembly version noise is retained without emitting false conflict issues");
        Contains(scanner, "validate_database_health", "scanner performs integrity, foreign-key and projection-consistency validation");
        Contains(scanner, "SAVEPOINT omega_scan_persist", "each scan persistence write is rollback-safe");
        Contains(scanner, "--max-batch-seconds", "scanner can stop starting scans before the workflow wall-clock limit");
        Contains(scanner, "--hardening-self-test", "scanner includes a deterministic catalog-scale/pathological-input stress fixture");
        Contains(scanner, "dependency_hardening_version", "scanner marks catalogs that passed the hardening projection checks");

        var buildInfo = File.ReadAllText(Path.Combine(Root, "Omega", "BuildInfo.cs"));
        Contains(buildInfo, "BuildStamp = \"omega-", "production build stamp is release-oriented rather than development-phase oriented");
        False(buildInfo.Contains("stage", StringComparison.OrdinalIgnoreCase), "production build stamp does not expose development phase labels");
        False(buildInfo.Contains("repair", StringComparison.OrdinalIgnoreCase), "production build stamp does not expose repair labels");

        var workflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "security-scanner.yml"));
        var normalizedWorkflow = workflow.ReplaceLineEndings("\n");
        Contains(normalizedWorkflow, "cron: \"17 6 * * *\"", "security scanner runs daily");
        Contains(normalizedWorkflow, "workflows:\n      - \"Omega SQLite catalog builder\"", "security scanner runs after successful catalog builds");
        Contains(normalizedWorkflow, "tools/catalog/security_scan.py", "scanner code changes trigger immediate repository-side validation");
        Contains(normalizedWorkflow, "github.event.workflow_run.conclusion == 'success'", "failed catalog builds cannot start a publish scan");
        Contains(normalizedWorkflow, "actions: read", "security scan can read the exact upstream catalog artifact");
        Contains(normalizedWorkflow, "contents: read", "hostile artifact scan job has read-only repository permission");
        False(workflow.Contains("contents: write", StringComparison.Ordinal), "security scanner never receives repository write permission");
        Contains(workflow, "name: omega-security-catalog", "security enrichment hands its database to the post-scan compactor as an Actions artifact");
        Contains(workflow, "--max-scans", "daily scan work is bounded");
        Contains(workflow, "--max-batch-seconds", "workflow supplies a wall-clock scan-start budget below the job timeout");
        Contains(workflow, "--hardening-self-test", "workflow runs the catalog/pathological-input hardening fixture");
        Contains(workflow, "--rescan-after-hours", "unchanged artifacts are periodically revalidated");
        Contains(workflow, "security-report.json", "each batch publishes an auditable scan summary");
        Contains(workflow, "tools/catalog/validate_security_catalog.py", "workflow delegates security persistence checks to tested Python validation");
        Contains(workflow, "--name omega-sqlite-catalog", "security scan consumes the exact catalog-builder artifact instead of an intermediate release");
        var securityValidator = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "validate_security_catalog.py"));
        Contains(securityValidator, "plugin_security_dependencies", "validator checks dependency intelligence persistence");
        Contains(securityValidator, "plugin_security_permission_candidates", "validator checks permission candidate persistence");
        Contains(securityValidator, "plugin_security_managed_assemblies", "validator checks managed assembly metadata persistence");
        Contains(securityValidator, "plugin_security_managed_symbols", "validator checks managed symbol persistence");
        Contains(securityValidator, "plugin_security_managed_calls", "validator checks compiled IL call-site persistence");
        Contains(securityValidator, "plugin_security_managed_reachability", "validator checks bounded reachability persistence");
        Contains(securityValidator, "plugin_security_dependency_resolutions", "validator checks catalog cross-reference edges");
        Contains(securityValidator, "plugin_security_dependency_components", "validator checks shared dependency component aggregation");
        Contains(securityValidator, "plugin_security_dependency_issues", "validator checks version/missing dependency issue persistence");
        Contains(securityValidator, "plugin_security_dependency_advisory_matches", "validator checks advisory match projection");
        Contains(securityValidator, "plugin_security_scan_lineage", "validator checks scan lineage persistence");
        Contains(securityValidator, "plugin_security_dependency_drift", "validator checks historical dependency drift persistence");
        Contains(securityValidator, "plugin_security_source_artifact_comparisons", "validator checks source/artifact comparison persistence");
        Contains(securityValidator, "foreign_key_check", "validator refuses catalogs with foreign-key violations");
        Contains(securityValidator, "security_revision_candidate", "validator checks semantic security revision metadata");

        var builder = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "build_sqlite_catalog.py"));
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_scans", "catalog schema preserves security scan history");
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_findings", "catalog schema stores individual findings");
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_current", "catalog schema stores current per-variant security state");
        Contains(builder, "security_status", "runtime catalog view exposes security state to Omega");
        Contains(builder, "catalog_base_revision", "catalog builder computes a stable semantic base revision");
        var revisions = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "catalog_revisions.py"));
        Contains(revisions, "omega.catalog-revision.v1", "catalog revision semantics have an explicit schema");
        Contains(revisions, "omega.security-revision.v2", "security revision semantics have an explicit schema");
        Contains(revisions, "omega.security-evidence-revision.v1", "detailed evidence revision semantics have an explicit schema");
        Contains(revisions, "CREATE TABLE IF NOT EXISTS catalog_changelog", "semantic catalog changes are persisted inside SQLite");
        Contains(revisions, "scan timestamps", "revision implementation explicitly excludes scan timestamps from semantic identity");
        Contains(revisions, "append_changelog_if_changed", "changelog rows are appended only for semantic catalog changes");

        var store = File.ReadAllText(Path.Combine(Root, "Omega", "Services", "SqliteCatalogStore.cs"));
        Contains(store, "SecurityArtifactSha256", "runtime reads exact scanned artifact hashes");
        Contains(store, "ReadSecurityFindings", "runtime reads structured security findings from SQLite");
        Contains(store, "catalog_revision", "runtime reads semantic Catalog Revision metadata");
        Contains(store, "security_revision", "runtime reads semantic Security Revision metadata");
        Contains(store, "evidence_revision", "runtime reads server-side Evidence Revision metadata without downloading evidence");
        Contains(store, "security_dependencies_json", "runtime reads the bounded dependency summary from Definitions");
        Contains(store, "ReadDependencies", "runtime deserializes structured dependency summaries");
        var dependencyModel = File.ReadAllText(Path.Combine(Root, "Omega", "Models", "MarketplaceDependency.cs"));
        Contains(dependencyModel, "TargetInternalName", "dependency summaries retain resolved Omega plugin targets");
        Contains(dependencyModel, "WarningSeverity", "dependency summaries retain warning/advisory severity without detailed evidence");

        var onlineClient = File.ReadAllText(Path.Combine(Root, "Omega", "Services", "OnlineCatalogClient.cs"));
        Contains(onlineClient, "CatalogRevision", "online descriptor carries Catalog Revision diagnostics");
        Contains(onlineClient, "SecurityRevision", "online descriptor carries Security Revision diagnostics");
        Contains(onlineClient, "EvidenceRevision", "online marketplace descriptor carries Evidence Revision diagnostics");
        Contains(onlineClient, "DatabaseRole", "online descriptor explicitly identifies the client marketplace database role");
        Contains(onlineClient, "DetailedSecurityEvidenceIncluded", "client rejects descriptors that attempt to ship detailed evidence");
        Contains(store, "database_role", "SQLite validation rejects a server-side evidence database while allowing legacy bootstrap catalogs");
        Contains(store, "runtimeColumns.Contains(\"security_automation_level\")", "older security-enriched catalogs remain readable before automation columns exist");
        False(onlineClient.Contains("security-evidence-latest", StringComparison.Ordinal), "Omega client contains no security-evidence release endpoint");
        False(onlineClient.Contains("omega-security-evidence.sqlite.zip", StringComparison.Ordinal), "Omega client cannot download the detailed evidence database");
        Contains(onlineClient, "64L * 1024 * 1024", "client transport ceiling accommodates compacted production catalogs while remaining bounded");

        var about = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Security.cs"));
        Contains(about, "About Omega", "version footer opens a dedicated About surface");
        Contains(about, "DrawAboutIdentityHero", "About gives the Omega identity its own visual hero");
        Contains(about, "const float iconSize = 112f", "About presents the application icon at a useful size");
        Contains(about, "omegaIconTexture?.GetWrapOrDefault()", "About uses the packaged Omega application artwork");
        Contains(about, "Definitions Revision", "About displays the semantic Definitions identity");
        Contains(about, "Security Revision", "About displays the semantic security identity");
        Contains(about, "Evidence Revision", "About displays the server-side evidence identity for troubleshooting");
        False(about.Contains("Catalog identity", StringComparison.Ordinal), "Settings/About no longer labels Definitions as a catalog database identity");

        var product = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.PluginSecurity.cs"));
        Contains(product, "Observed capabilities", "product page explains observed permissions/capabilities");
        Contains(product, "Detailed findings", "product page exposes expandable detailed findings");
        Contains(product, "No findings is not proof", "product page avoids claiming that static analysis proves safety");
        Contains(product, "The published package was not verified to match that source.", "product page preserves source provenance uncertainty");
        Contains(product, "SecurityAutomationCapabilities.Count > 0", "product page renders structured character/menu automation evidence when present");
        Contains(product, "ImGui.TextUnformatted(\"Automation\")", "product page labels the structured automation section clearly");
        Contains(product, "AutomationLevelLabel(plugin.SecurityAutomationLevel)", "product page renders the normalized automation classification");
        Contains(product, "Full gameplay automation", "product page can distinguish the strongest automation class");
        DoesNotContain(product, "Highest:", "product hero severity badge uses a concise risk label");
        Contains(product, "\"high\" => \"High\"", "high severity is displayed simply as High");
        Contains(product, "\"caution\" => \"Medium\"", "caution severity is presented as the user-facing Medium level");
        Contains(product, "\"informational\" => \"Low\"", "informational severity is presented as the user-facing Low level");
        Contains(product, "Scanned {scanned.ToLocalTime():g}", "scan timestamp is retained in the detailed security section");
        Contains(product, "Findings:", "detailed security section retains severity counts away from the hero");
        Contains(product, "DrawSecurityBulletList", "observed capabilities render as readable vertical bullets instead of one dense line");
        var dependenciesUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Dependencies.cs"));
        Contains(dependenciesUi, "Dependencies", "product page exposes a dedicated dependency section");
        Contains(dependenciesUi, "Available in Omega", "resolved plugin dependencies advertise that they can be opened in Omega");
        Contains(dependenciesUi, "OpenPluginDetails", "resolved plugin dependencies navigate to their Omega product page");
        Contains(dependenciesUi, "Provided by framework", "framework-provided dependencies are distinguished from installable plugin dependencies");
        Contains(dependenciesUi, "Definitions keeps this summary bounded", "dependency UI explains bounded client projection rather than implying forensic completeness");
        var productPage = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.ProductPage.cs"));
        Contains(productPage, "DrawProductSourcePackages(plugin)", "product page exposes source-package provenance before dependency/security detail");
        Contains(productPage, "DrawProductDependencies(plugin, installed)", "Dependencies render between package provenance and Security on the product page");

        var packagesUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.SourcePackages.cs"));
        Contains(packagesUi, "Packages & repositories", "product page explains distinct downloadable source packages");
        Contains(packagesUi, "SecurityArtifactSha256", "scanned package hashes collapse repository mirrors that point at the same artifact");
        Contains(packagesUi, "Repository manifests pointing to this package", "each package lists the repository manifests that reference it");
        Contains(packagesUi, "OrderByDescending(x => x.Official)", "official repository references are presented first");

        var discoverUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Discover.cs"));
        Contains(discoverUi, "FindRequiredDependencyAutomation", "risk resolver follows required plugin dependencies for automation exposure");
        Contains(discoverUi, "Automation exposure through required dependency", "dependency-provided automation is explained in the risk tooltip");
        Contains(discoverUi, "maximumDependencyRiskDepth = 8", "recursive dependency-risk traversal remains bounded");
        Contains(discoverUi, "FontAwesomeIcon.ExclamationTriangle", "risk findings use the standard Font Awesome warning-triangle glyph");
        Contains(discoverUi, "UiBuilder.IconFontFixedWidth", "risk glyphs use Dalamud's fixed-width Font Awesome font for stable alignment");
        Contains(discoverUi, "var glyphSize = ImGui.CalcTextSize(glyph)", "risk glyph centering is derived from measured glyph bounds");
        Contains(discoverUi, "(size - glyphSize.X) * 0.5f", "risk glyphs remain horizontally centered without punctuation-specific offsets");
        Contains(discoverUi, "(size - glyphSize.Y) * 0.5f", "risk glyphs remain vertically centered without punctuation-specific offsets");
        DoesNotContain(discoverUi, "DrawPluginWarningTriangle", "the obsolete hand-drawn warning triangle renderer must not return");
    }
    internal static void TestCatalogCompactionWorkflowContract()
    {
        var compactor = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "compact_sqlite_catalog.py"));
        Contains(compactor, "COMPACTOR_VERSION = \"1.2.0\"", "database compactor version is explicit");
        Contains(compactor, "omega.plugin-security.scan-summary.v1", "redundant scan JSON is converted to a bounded summary schema");
        Contains(compactor, "runtime_projection_digest", "compactor hashes the complete runtime projection before and after rewriting");
        Contains(compactor, "preserved_counts", "compactor verifies historical and normalized evidence row counts are preserved");
        Contains(compactor, "VACUUM INTO", "compactor writes a fresh SQLite database instead of leaving free pages behind");
        Contains(compactor, "MAX_SUMMARY_BYTES = 64 * 1024", "historical summary payloads remain bounded");
        Contains(compactor, "plugin_security_managed_calls", "managed IL call evidence remains preserved during compaction");
        Contains(compactor, "plugin_security_dependency_drift", "historical dependency drift remains preserved during compaction");
        Contains(compactor, "--self-test", "compactor includes an isolated history-preservation regression fixture");
        Contains(compactor, "append_changelog_if_changed", "compactor finalizes semantic revisions and changelog before publication");
        Contains(compactor, "publication_required", "compactor records a semantic publication decision");
        Contains(compactor, "catalogRevision", "compactor writes the catalog revision into the production descriptor");
        Contains(compactor, "securityRevision", "compactor writes the security revision into the production descriptor");
        Contains(compactor, "changelogEntryCount", "descriptor exposes embedded changelog size for troubleshooting");
        var projector = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "project_marketplace_catalog.py"));
        Contains(projector, "PROJECTOR_VERSION = \"1.1.0\"", "marketplace projector version is explicit");
        Contains(projector, "marketplace_security_current", "client database retains only compact current security summaries");
        Contains(projector, "DEPENDENCY_SUMMARY_LIMIT = 30", "Definitions dependency projection remains bounded per plugin variant");
        Contains(projector, "build_dependency_summaries", "projector derives compact dependencies from detailed server-side evidence before dropping it");
        Contains(projector, "dependencies_json", "compact dependency summaries survive in the marketplace security projection");
        Contains(projector, "dependency_total_count", "Definitions retains the full dependency count when the displayed summary is truncated");
        Contains(projector, "DROP TABLE", "projector physically removes detailed security tables from the client database");
        Contains(projector, "detailedSecurityEvidenceIncluded", "marketplace descriptor explicitly excludes detailed security evidence");


        var workflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "catalog-compaction.yml"));
        var normalized = workflow.ReplaceLineEndings("\n");
        Contains(normalized, "workflows:\n      - \"Omega plugin security scanner\"", "compaction runs after the security scanner workflow completes");
        Contains(normalized, "github.event.workflow_run.conclusion == 'success'", "failed security scans cannot start production compaction");
        Contains(workflow, "gh run download", "automatic compaction consumes the exact security workflow artifact");
        Contains(workflow, "omega-security-catalog", "compaction consumes security-enriched catalog artifacts");
        Contains(workflow, "compaction-report.json", "compaction publishes an auditable size and integrity report");
        Contains(workflow, "name: Publish client marketplace catalog", "small marketplace database is promoted to the client release");
        Contains(workflow, "name: Publish server-side security evidence database", "detailed evidence is published separately");
        Contains(workflow, "omega-marketplace.sqlite.zip", "client release uses the small marketplace bundle");
        Contains(workflow, "omega-security-evidence.sqlite.zip", "server-side release retains detailed evidence");
        Contains(workflow, "security-evidence-latest", "detailed evidence has a separate stable release");
        Contains(workflow, "contents: write", "repository write permission is isolated to the final compaction publish job");
        Contains(workflow, "tools/catalog/validate_marketplace_catalog.py", "compaction validates the projected client marketplace database before publication");
        Contains(workflow, "tools/catalog/validate_evidence_catalog.py", "compaction validates the detailed evidence database before publication");
        Contains(compactor, "validate_compacted_database", "compactor validates its intermediate compacted evidence database before projection");
        Contains(workflow, "tools/catalog/publication_decision.py", "compaction uses tested fail-closed publication decision logic");
        Contains(workflow, "needs: [compact, publish_evidence]", "marketplace publication waits for the evidence publication decision");
        Contains(workflow, "needs.publish_evidence.result == 'success'", "marketplace publication cannot expose an evidence revision before required evidence publication succeeds");
        Contains(workflow, "--previous-database", "compaction compares against the previous production database for changelog generation");
        Contains(workflow, "tools/catalog/compact_sqlite_catalog.py", "compactor code changes can compact the current production release immediately");
        var publishStart = normalized.IndexOf("\n  publish_marketplace:\n", StringComparison.Ordinal);
        var ledgerStart = normalized.IndexOf("\n  publish_evidence:\n", publishStart + 1, StringComparison.Ordinal);
        True(publishStart >= 0 && ledgerStart > publishStart, "compactor publish job can be isolated for verification contracts");
        var publishBlock = normalized[publishStart..ledgerStart];
        var checkoutIndex = publishBlock.IndexOf("actions/checkout@v6", StringComparison.Ordinal);
        var setupPythonIndex = publishBlock.IndexOf("actions/setup-python@v7", StringComparison.Ordinal);
        var remoteVerifyIndex = publishBlock.IndexOf("tools/catalog/validate_marketplace_catalog.py", StringComparison.Ordinal);
        True(checkoutIndex >= 0 && remoteVerifyIndex > checkoutIndex, "marketplace publish job checks out repository before running the published-catalog validator");
        True(setupPythonIndex >= 0 && remoteVerifyIndex > setupPythonIndex, "marketplace publish job configures Python before running the published-catalog validator");
        var compactValidator = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "validate_compacted_catalog.py"));
        Contains(compactValidator, "foreign_key_check", "compaction validator refuses foreign-key violations");
        Contains(compactValidator, "catalog_changelog", "compaction validator requires the embedded changelog");
        Contains(compactValidator, "catalogRevision", "compaction validator checks descriptor/database revision identity");
    }

}
