namespace Dalagab.Omega.RegressionTests;

internal static partial class RegressionCases
{
    internal static void TestPluginSecurityIntelligenceContract()
    {
        var scanner = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "security_scan.py"));
        Contains(scanner, "SCANNER_VERSION = \"2.5.0\"", "scanner version is explicit so stale scans can be refreshed");
        Contains(scanner, "Only HTTPS downloads are scanned", "scanner refuses insecure artifact transports");
        Contains(scanner, "MAX_ARTIFACT_BYTES", "artifact downloads are bounded");
        Contains(scanner, "MAX_ARTIFACT_BYTES = 256 * 1024 * 1024", "artifact download ceiling accommodates large production plugin packages while remaining bounded");
        Contains(scanner, "MAX_ARCHIVE_UNCOMPRESSED = 512 * 1024 * 1024", "archive expansion remains bounded above large production packages");
        Contains(scanner, "MAX_ARCHIVE_ENTRIES", "archive entry count is bounded");
        Contains(scanner, "MAX_ARCHIVE_ENTRIES = 16_384", "archive ceiling accommodates legitimate multi-thousand-entry plugin packages while remaining bounded");
        Contains(scanner, "many_metadata[\"files\"] == 3000", "hardening suite proves packages above the former 1,024-entry ceiling remain scannable");
        Contains(scanner, "safe_member_name", "archive paths are validated before content inspection");
        Contains(scanner, "never", "scanner documents its no-execution trust boundary");
        Contains(scanner, "compound.network-execute", "compound network/process risk is surfaced");
        Contains(scanner, "sourceToBinaryVerified", "source inspection does not imply source-to-binary verification");
        Contains(scanner, "source_candidates(", "source scanning derives GitHub repositories from more than RepoUrl");
        Contains(scanner, "select_plugin_source_scope", "monorepo source scans are narrowed to the actual plugin build graph");
        Contains(scanner, "repository-context-only", "unrelated repository projects remain context instead of becoming plugin security evidence");
        Contains(scanner, "contextProjects", "sibling server and tooling projects remain visible as non-critical repository context");
        Contains(scanner, "project_closure", "plugin source scope follows transitive project references instead of traversing the whole repository");
        Contains(scanner, "source_override_key(", "human-reviewed source overrides use stable plugin/source identities instead of SQLite row ids");
        Contains(scanner, "sources/source-overrides.json", "validated public-source overrides remain a repository-side scanner input");
        Contains(scanner, "plugin_security_current", "scanner persists the current result per exact catalog variant");
        Contains(scanner, "plugin_security_automation_capabilities", "scanner persists structured character/menu automation evidence");
        Contains(scanner, "derive_automation_capabilities", "scanner derives bounded user-facing automation classifications");
        Contains(scanner, "game.character.move", "character movement control is classified explicitly");
        Contains(scanner, "game.character.execute_action", "character action execution is classified explicitly");
        Contains(scanner, "game.ui.callback", "game UI/menu callback control is classified explicitly");
        Contains(scanner, "automation.via_ipc", "automation supplied indirectly through IPC is classified explicitly");
        Contains(scanner, "Preserve last-known-good intelligence", "transient revalidation failures do not erase the last completed scan");

        Contains(scanner, "omega.plugin-security.dependencies.v2", "dependency inventory has an explicit machine-readable schema");
        Contains(scanner, "plugin_security_dependencies", "dependency records are persisted separately from security findings");
        Contains(scanner, "plugin_security_imports", "namespace/import evidence is persisted");
        Contains(scanner, "plugin_security_permission_candidates", "import/dependency evidence maps to explicit permission candidates");
        Contains(scanner, "PackageReference", "NuGet package references are inventoried");
        Contains(scanner, "ProjectReference", "project references are inventoried");
        Contains(scanner, "packages.lock.json", "locked NuGet dependency versions are inventoried");
        Contains(scanner, "project.assets.json", "resolved NuGet dependency versions are inventoried when present");
        Contains(scanner, "GetIpcSubscriber", "Dalamud IPC consumers are inventoried");
        Contains(scanner, "GetIpcProvider", "Dalamud IPC providers are inventoried separately from consumers");
        Contains(scanner, "plugin_security_ipc_endpoints", "historical IPC provider/consumer observations are persisted per scan");
        Contains(scanner, "plugin_security_ipc_registry", "current IPC providers are registered by exact channel identity");
        Contains(scanner, "resolved-ipc-provider", "IPC consumers can resolve to the plugin that exposes the channel");
        Contains(scanner, "exact-ipc-channel-provider", "IPC provider links use the exact Dalamud registration string rather than plugin-name guessing");
        Contains(scanner, "infer_ipc_consumer_relationship", "IPC consumers receive conservative required/feature/optional/unknown relationship inference");
        Contains(scanner, "missing-required-ipc-provider", "high-confidence required IPC providers become explicit dependency issues when absent");
        Contains(scanner, "relationship_confidence", "IPC relationship confidence is retained in normalized dependency evidence");
        Contains(scanner, "relationship_evidence_json", "IPC relationship evidence remains available server-side");
        Contains(scanner, "RequiredPlugins", "required external Dalamud plugin dependencies are inventoried from manifests");
        Contains(scanner, "OptionalPlugins", "soft external Dalamud plugin dependencies are preserved from manifests");
        Contains(scanner, "requirement", "dependency rows preserve required/soft/optional/bundled semantics");
        Contains(scanner, "DllImport", "native library imports are inventoried");
        Contains(scanner, "bundledManagedAssemblies", "managed libraries bundled in plugin packages are inventoried");
        Contains(scanner, "bundledNativeLibraries", "native libraries bundled in plugin packages are inventoried");
        Contains(scanner, "projectDependencySha256", "dependency/project declarations receive a stable fingerprint");
        Contains(scanner, "permissionCandidates", "dependency-derived permissions remain candidates rather than confirmed call-path findings");
        Contains(scanner, "parse_managed_pe", "managed PE metadata is parsed without loading assemblies");
        Contains(scanner, "#Strings", "managed metadata string heap is parsed directly");
        Contains(scanner, "managed-assembly-reference", "AssemblyRef dependencies are inventoried with resolved versions");
        Contains(scanner, "member-reference", "managed TypeRef/MemberRef symbols are inventoried");
        Contains(scanner, "ImplMap", "managed P/Invoke metadata is inventoried from ImplMap");
        Contains(scanner, "plugin_security_managed_assemblies", "managed assembly parse summaries are persisted");
        Contains(scanner, "plugin_security_managed_symbols", "managed metadata symbols are persisted for later call/diff analysis");
        Contains(scanner, "process.execute", "high-confidence metadata references can strengthen permission candidates without claiming runtime execution");
        Contains(scanner, "_decode_cil_calls", "compiled CIL method bodies are decoded without loading assemblies");
        Contains(scanner, "callvirt", "CIL virtual method call sites are recorded");
        Contains(scanner, "newobj", "CIL object-construction call sites are supported");
        Contains(scanner, "ldftn", "CIL function-pointer targets are recorded");
        Contains(scanner, "sourceMethodToken", "call-site evidence retains the containing compiled method token");
        Contains(scanner, "targetNativeLibrary", "calls to local P/Invoke stubs resolve to native libraries");
        Contains(scanner, "plugin_security_managed_calls", "compiled call-site evidence is persisted separately from metadata references");
        Contains(scanner, "targetMethodToken", "local compiled calls retain the exact MethodDef target token for graph traversal");
        Contains(scanner, "plugin_security_managed_reachability", "bounded local method reachability is persisted separately from call-site evidence");
        Contains(scanner, "MAX_MANAGED_REACHABILITY_DEPTH", "local graph traversal is depth bounded for hostile artifacts");
        Contains(scanner, "callback-name", "probable event callbacks can seed explicitly-labeled heuristic roots");
        Contains(scanner, "VeryHigh", "compiled call-site evidence strengthens permission confidence without claiming runtime reachability");
        Contains(scanner, "but it still does not prove that a runtime branch actually", "reachability evidence preserves the static-analysis runtime boundary");
        Contains(scanner, "plugin_security_dependency_resolutions", "current dependency rows are cross-referenced to catalog plugins/components");
        Contains(scanner, "plugin_security_dependency_components", "shared package/assembly/native/IPC dependencies receive reusable component identities");
        Contains(scanner, "resolved-plugin", "exact catalog plugin dependencies are represented as resolved plugin edges");
        Contains(scanner, "external-unresolved", "unresolved external and soft plugin dependencies remain visible instead of being dropped");
        Contains(scanner, "internal-name", "plugin dependency resolution prefers exact InternalName matches");
        Contains(scanner, "nuget:", "NuGet dependencies receive normalized component keys for cross-plugin usage queries");
        Contains(scanner, "refresh_dependency_graph", "dependency graph can be refreshed when catalog contents change without rescanning artifacts");
        Contains(scanner, "current completed scans only", "graph projection avoids duplicating historical scans in current dependency usage counts");
        Contains(scanner, "version_requirement", "dependency rows preserve declared version constraints separately from observed versions");
        Contains(scanner, "resolved_version", "resolved dependency versions are stored separately from declarations");
        Contains(scanner, "version_satisfies", "NuGet/plugin version constraints are evaluated conservatively");
        Contains(scanner, "unparsed-constraint", "unknown version syntax is not treated as an incompatibility");
        Contains(scanner, "plugin_security_dependency_issues", "missing dependencies and compatibility issues are persisted as a current projection");
        Contains(scanner, "missing-required-plugin", "required catalog plugin dependencies that cannot be resolved are surfaced explicitly");
        Contains(scanner, "soft-plugin-unresolved", "soft dependency absence remains visible without being treated as a hard failure");
        Contains(scanner, "major-version-divergence", "shared components at different major versions are surfaced conservatively as divergence");
        Contains(scanner, "not by itself proof of a runtime conflict", "component version divergence is not overstated as a definite conflict");
        Contains(scanner, "plugin_security_dependency_advisory_matches", "optional advisory enrichment is stored separately from dependency evidence");
        Contains(scanner, "load_advisories", "advisories are supplied locally rather than fetched by hostile-artifact analysis");
        Contains(scanner, "--advisories", "scanner exposes an optional advisory-document hook without making advisories mandatory");
        Contains(scanner, "plugin_security_scan_lineage", "successive completed scans retain immutable lineage to the previous current scan");
        Contains(scanner, "plugin_security_dependency_drift", "dependency and permission changes are persisted as historical drift events");
        Contains(scanner, "plugin_security_source_artifact_comparisons", "source declarations and compiled-artifact dependency observations are compared per scan");
        Contains(scanner, "artifact-and-source-changed", "drift events preserve whether binary and source both changed");
        Contains(scanner, "scanner-changed", "scanner-only enrichment changes are distinguishable from plugin release changes");
        Contains(scanner, "dependency-added", "dependency additions are explicit historical events");
        Contains(scanner, "version-changed", "dependency version drift is explicit historical evidence");
        Contains(scanner, "permission-added", "new permission candidates are tracked between scans");
        Contains(scanner, "compared-not-verified", "source/artifact comparison never claims reproducible source-to-binary verification");
        Contains(scanner, "MAX_DRIFT_EVENTS_PER_SCAN", "drift generation is bounded for hostile or pathological inputs");
        Contains(scanner, "Exercise the real persistence path", "scanner self-test covers the SQLite write path");
        Contains(scanner, "ValidatingRedirectHandler", "scanner validates redirects before following them and strips cross-host authorization");
        Contains(scanner, "duplicate normalized path", "scanner rejects ambiguous duplicate archive paths");
        Contains(scanner, "symbolic-link entry", "scanner rejects ZIP symbolic-link entries even though archives are never extracted");
        Contains(scanner, "MAX_DEPENDENCY_RECORDS_PER_SCAN", "scanner caps per-scan dependency evidence");
        Contains(scanner, "_identityMaps", "scanner uses ephemeral per-scan identity maps instead of quadratic evidence deduplication");
        Contains(scanner, "droppedByCollection", "bounded evidence truncation is explicit rather than silent");
        Contains(scanner, "MAX_CURRENT_DEPENDENCY_ROWS", "scanner bounds current graph materialization before loading it into memory");
        Contains(scanner, "MAX_ADVISORIES", "scanner bounds advisory input size");
        Contains(scanner, "MAX_ADVISORY_MATCHES", "scanner bounds advisory projection amplification");
        Contains(scanner, "platform-version-variation", "framework assembly version noise is retained without emitting false conflict issues");
        Contains(scanner, "validate_database_health", "scanner performs integrity, foreign-key and projection-consistency validation");
        Contains(scanner, "SAVEPOINT omega_scan_persist", "each scan persistence write is rollback-safe");
        Contains(scanner, "--max-batch-seconds", "scanner can stop starting scans before the workflow wall-clock limit");
        Contains(scanner, "--hardening-self-test", "scanner includes a deterministic catalog-scale/pathological-input stress fixture");
        Contains(scanner, "dependency_hardening_version", "scanner marks catalogs that passed the hardening projection checks");

        var buildInfo = File.ReadAllText(Path.Combine(Root, "Omega", "BuildInfo.cs"));
        Contains(buildInfo, "BuildStamp = \"omega-", "production build stamp is release-oriented rather than internal-workflow oriented");
        Equal(2, buildInfo.Split("public const string", StringSplitOptions.None).Length - 1, "production build metadata contains only the release version and release stamp constants");
        False(buildInfo.Contains("repair", StringComparison.OrdinalIgnoreCase), "production build stamp does not expose repair labels");

        var workflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "security-scanner.yml"));
        var normalizedWorkflow = workflow.ReplaceLineEndings("\n");
        Contains(normalizedWorkflow, "cron: \"47 3,15 * * *\"", "security scanner has twice-daily independent safety-net runs");
        Contains(normalizedWorkflow, "workflows:\n      - \"Omega SQLite catalog builder\"", "security scanner runs after successful catalog builds");
        Contains(normalizedWorkflow, "tools/catalog/security_scan.py", "scanner code changes trigger immediate repository-side validation");
        Contains(normalizedWorkflow, "github.event.workflow_run.conclusion == 'success'", "failed catalog builds cannot start a publish scan");
        Contains(normalizedWorkflow, "actions: read", "security scan can read the exact upstream catalog artifact");
        Contains(normalizedWorkflow, "contents: write", "final validated v2 snapshot publication has repository write permission");
        Contains(workflow, "ref: security-evidence-v2", "scanner begins from the last-known-good v2 evidence snapshot");
        Contains(workflow, "production_security_v2_pipeline.py", "security scanning is staged through the production v2 orchestrator");
        var productionV2Pipeline = File.ReadAllText(Path.Combine(Root, "tools", "security", "production_security_v2_pipeline.py"));
        Contains(productionV2Pipeline, "collect_from_nuget_index", "production OSV queries are driven from the v2 NuGet evidence index");
        Contains(productionV2Pipeline, "NuGet evidence-index publication gate", "production fails closed when exact NuGet observations are not actually queried");
        Contains(scanner, ".deps.json", "packaged .deps.json files are inspected for exact resolved NuGet package versions");
        Contains(workflow, "publish_security_evidence_v2.py", "validated v2 publication is an explicit final step");
        Contains(workflow, "--snapshot-validation-report", "v2 push requires intrinsic snapshot validation");
        Contains(workflow, "--audit-report", "v2 push requires the independent developer audit");
        Contains(workflow, "--max-scans", "scheduled scan work is bounded");
        Contains(workflow, "--max-batch-seconds", "workflow supplies a wall-clock scan-start budget below the job timeout");
        Contains(workflow, "--hardening-self-test", "workflow runs the catalog/pathological-input hardening fixture");
        Contains(workflow, "--rescan-after-hours", "unchanged artifacts are periodically revalidated");
        Contains(workflow, "production-security-v2-report.json", "each batch retains an auditable v2 production summary");
        Contains(workflow, "tools/catalog/validate_marketplace_catalog.py", "workflow validates the small client projection before publication");
        Contains(workflow, "--name omega-sqlite-catalog", "security scan consumes the exact catalog-builder artifact instead of an intermediate release");
        False(workflow.Contains("omega-security-evidence.sqlite.zip", StringComparison.Ordinal), "production scanner no longer transports the giant v1 evidence SQLite database");
        var securityValidator = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "validate_security_catalog.py"));
        Contains(securityValidator, "plugin_security_dependencies", "validator checks dependency intelligence persistence");
        Contains(securityValidator, "plugin_security_permission_candidates", "validator checks permission candidate persistence");
        Contains(securityValidator, "plugin_security_managed_assemblies", "validator checks managed assembly metadata persistence");
        Contains(securityValidator, "plugin_security_managed_symbols", "validator checks managed symbol persistence");
        Contains(securityValidator, "plugin_security_managed_calls", "validator checks compiled IL call-site persistence");
        Contains(securityValidator, "plugin_security_managed_reachability", "validator checks bounded reachability persistence");
        Contains(securityValidator, "plugin_security_dependency_resolutions", "validator checks catalog cross-reference edges");
        Contains(securityValidator, "plugin_security_dependency_components", "validator checks shared dependency component aggregation");
        Contains(securityValidator, "plugin_security_ipc_endpoints", "validator requires persisted IPC endpoint observations");
        Contains(securityValidator, "plugin_security_ipc_registry", "validator requires the current IPC provider registry");
        Contains(securityValidator, "resolved IPC edges are missing provider registrations", "validator rejects IPC edges that cannot be backed by a registered provider");
        Contains(securityValidator, "plugin_security_dependency_issues", "validator checks version/missing dependency issue persistence");
        Contains(securityValidator, "plugin_security_dependency_advisory_matches", "validator checks advisory match projection");
        Contains(securityValidator, "plugin_security_scan_lineage", "validator checks scan lineage persistence");
        Contains(securityValidator, "plugin_security_dependency_drift", "validator checks historical dependency drift persistence");
        Contains(securityValidator, "plugin_security_source_artifact_comparisons", "validator checks source/artifact comparison persistence");
        Contains(securityValidator, "foreign_key_check", "validator refuses catalogs with foreign-key violations");
        Contains(securityValidator, "security_revision_candidate", "validator checks semantic security revision metadata");

        var builder = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "build_sqlite_catalog.py"));
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_scans", "catalog schema preserves security scan history");
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_findings", "catalog schema stores individual findings");
        Contains(builder, "CREATE TABLE IF NOT EXISTS plugin_security_current", "catalog schema stores current per-variant security state");
        Contains(builder, "security_status", "runtime catalog view exposes security state to Omega");
        Contains(builder, "catalog_base_revision", "catalog builder computes a stable semantic base revision");
        var revisions = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "catalog_revisions.py"));
        Contains(revisions, "omega.catalog-revision.v1", "catalog revision semantics have an explicit schema");
        Contains(revisions, "omega.security-revision.v2", "security revision semantics have an explicit schema");
        Contains(revisions, "omega.security-evidence-revision.v1", "detailed evidence revision semantics have an explicit schema");
        Contains(revisions, "CREATE TABLE IF NOT EXISTS catalog_changelog", "semantic catalog changes are persisted inside SQLite");
        Contains(revisions, "scan timestamps", "revision implementation explicitly excludes scan timestamps from semantic identity");
        Contains(revisions, "append_changelog_if_changed", "changelog rows are appended only for semantic catalog changes");

        var store = File.ReadAllText(Path.Combine(Root, "Omega", "Services", "SqliteCatalogStore.cs"));
        Contains(store, "SecurityArtifactSha256", "runtime reads exact scanned artifact hashes");
        Contains(store, "ReadSecurityFindings", "runtime reads structured security findings from SQLite");
        Contains(store, "catalog_revision", "runtime reads semantic Catalog Revision metadata");
        Contains(store, "security_revision", "runtime reads semantic Security Revision metadata");
        Contains(store, "evidence_revision", "runtime reads server-side Evidence Revision metadata without downloading evidence");
        Contains(store, "security_dependencies_json", "runtime reads the bounded dependency summary from Definitions");
        Contains(store, "ReadDependencies", "runtime deserializes structured dependency summaries");
        var dependencyModel = File.ReadAllText(Path.Combine(Root, "Omega", "Models", "MarketplaceDependency.cs"));
        Contains(dependencyModel, "TargetInternalName", "dependency summaries retain resolved Omega plugin targets");
        Contains(dependencyModel, "WarningSeverity", "dependency summaries retain warning/advisory severity without detailed evidence");

        var onlineClient = File.ReadAllText(Path.Combine(Root, "Omega", "Services", "OnlineCatalogClient.cs"));
        Contains(onlineClient, "CatalogRevision", "online descriptor carries Catalog Revision diagnostics");
        Contains(onlineClient, "SecurityRevision", "online descriptor carries Security Revision diagnostics");
        Contains(onlineClient, "EvidenceRevision", "online marketplace descriptor carries Evidence Revision diagnostics");
        Contains(onlineClient, "DatabaseRole", "online descriptor explicitly identifies the client marketplace database role");
        Contains(onlineClient, "DetailedSecurityEvidenceIncluded", "client rejects descriptors that attempt to ship detailed evidence");
        Contains(store, "database_role", "SQLite validation rejects a server-side evidence database while allowing legacy bootstrap catalogs");
        Contains(store, "runtimeColumns.Contains(\"security_automation_level\")", "older security-enriched catalogs remain readable before automation columns exist");
        False(onlineClient.Contains("security-evidence-latest", StringComparison.Ordinal), "Omega client contains no security-evidence release endpoint");
        False(onlineClient.Contains("omega-security-evidence.sqlite.zip", StringComparison.Ordinal), "Omega client cannot download the detailed evidence database");
        Contains(onlineClient, "64L * 1024 * 1024", "client transport ceiling accommodates compacted production catalogs while remaining bounded");

        var about = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Security.cs"));
        Contains(about, "About Omega", "version footer opens a dedicated About surface");
        Contains(about, "DrawAboutIdentityHero", "About gives the Omega identity its own visual hero");
        Contains(about, "const float iconSize = 112f", "About presents the application icon at a useful size");
        Contains(about, "omegaIconTexture?.GetWrapOrDefault()", "About uses the packaged Omega application artwork");
        Contains(about, "Every plugin. One orbit.", "About leads with Omega's product tagline");
        Contains(about, "/omega   /omg", "About advertises both commands that open Omega");
        Contains(about, "Find more. Know more. Install with confidence.", "About sells the core discovery and trust workflow");
        Contains(about, "DrawAboutVersionAndDefinitions", "About presents the application version and Definitions as separate moving parts");
        DoesNotContain(about, "The installed Omega application release", "About keeps Version concise instead of explaining the obvious application version label");
        Contains(about, "Definitions are Omega's independently updated marketplace data", "About explains what Definitions contain and that they update independently");
        Contains(about, "omega-about-scrollable-body", "About keeps the identity and Definitions fixed while lower product/help content can scroll");
        Contains(about, "const float leftInset = 12f", "About identity hero is aligned toward the content edge instead of being centered in the modal");
        Contains(about, "DrawAboutWrappedBullet", "About wraps long lower-section bullet copy instead of allowing horizontal clipping");
        Contains(about, "catalog.CatalogRevision", "About shows the currently loaded Definitions revision when available");
        DoesNotContain(about, "Security Revision", "About does not expose internal security revision identity");
        DoesNotContain(about, "Evidence Revision", "About does not expose server-side evidence identity");
        DoesNotContain(about, "Definitions changelog entries", "About does not expose internal changelog counts");

        var product = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.PluginSecurity.cs"));
        Contains(product, "Observed capabilities", "product page explains observed permissions/capabilities");
        Contains(product, "Detailed findings", "product page exposes expandable detailed findings");
        Contains(product, "No findings is not proof", "product page avoids claiming that static analysis proves safety");
        Contains(product, "The published package was not verified to match that source.", "product page preserves source provenance uncertainty");
        Contains(product, "SecurityAutomationCapabilities.Count > 0", "product page renders structured character/menu automation evidence when present");
        Contains(product, "ImGui.TextUnformatted(\"Automation\")", "product page labels the structured automation section clearly");
        Contains(product, "AutomationLevelLabel(plugin.SecurityAutomationLevel)", "product page renders the normalized automation classification");
        Contains(product, "Full gameplay automation", "product page can distinguish the strongest automation class");
        DoesNotContain(product, "Highest:", "product hero severity badge uses a concise risk label");
        Contains(product, "\"high\" => new PluginSecurityVisual", "high severity has an explicit shared card/product visual");
        Contains(product, "\"caution\" or \"medium\" => new PluginSecurityVisual", "caution severity is presented through the shared Medium visual");
        Contains(product, "\"informational\" or \"low\" => new PluginSecurityVisual", "informational severity is presented through the shared Low visual");
        Contains(product, "\"No findings\"", "completed no-finding scans use the same user-facing label on cards and product pages");
        Contains(product, "Scanned {scanned.ToLocalTime():g}", "scan timestamp is retained in the detailed security section");
        Contains(product, "Findings:", "detailed security section retains severity counts away from the hero");
        Contains(product, "DrawSecurityBulletList", "observed capabilities render as readable vertical bullets instead of one dense line");
        var dependenciesUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Dependencies.cs"));
        Contains(dependenciesUi, "Dependencies", "product page exposes a dedicated dependency section");
        Contains(dependenciesUi, "DrawDependencyEmptyState", "dependency section stays visible even when a package has no projected dependency rows");
        Contains(dependenciesUi, "No external plugin or IPC dependencies were detected for this package.", "completed scans explain a genuine zero plugin-dependency result");
        Contains(dependenciesUi, "Dependency information is not present in the current Definitions snapshot for this package.", "older or unscanned Definitions snapshots explain missing dependency data instead of hiding the view");
        DoesNotContain(dependenciesUi, "if (!plugin.HasCompletedSecurityScan || plugin.SecurityDependencyTotalCount <= 0 || plugin.SecurityDependencies.Count == 0)", "dependency section must not disappear behind the old security/dependency guard");
        Contains(dependenciesUi, "Available in Omega", "resolved plugin dependencies advertise that they can be opened in Omega");
        Contains(dependenciesUi, "Provided by {dependency.TargetInternalName}", "resolved IPC consumers name the plugin that provides the channel");
        Contains(dependenciesUi, "Required plugins / providers", "required IPC providers are presented alongside required plugin dependencies");
        Contains(dependenciesUi, "Feature integrations", "feature-scoped IPC relationships receive their own dependency group");
        Contains(dependenciesUi, "IsHighConfidenceRequiredProvider", "required-provider warnings are limited to strong relationship evidence");
        Contains(dependenciesUi, "RelationshipReason", "bounded relationship evidence is explainable from the dependency UI");
        Contains(dependenciesUi, "Multiple IPC providers observed", "ambiguous IPC provider registrations remain explicit instead of being guessed");
        Contains(dependenciesUi, "OpenPluginDetails", "resolved plugin dependencies navigate to their Omega product page");
        Contains(dependenciesUi, "IsDisplayablePluginDependency", "dependency UI filters legacy Definitions rows to plugin and IPC relationships");
        Contains(dependenciesUi, "dependency.IsFramework", "framework dependencies are explicitly excluded from the product dependency panel");
        DoesNotContain(dependenciesUi, "Provided by framework", "framework components are not presented as plugin dependencies");
        DoesNotContain(dependenciesUi, "Bundled / observed", "implementation components do not get a dependency group");
        var productPage = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.ProductPage.cs"));
        Contains(productPage, "DrawProductDependencies(plugin, installed)", "product page always includes the dependency view");
        True(
            productPage.IndexOf("DrawProductDependencies(plugin, installed)", StringComparison.Ordinal) <
            productPage.IndexOf("DrawProductSourcePackages(plugin, sourcePackages, currentApi, currentDalamudVersion)", StringComparison.Ordinal),
            "Dependencies render before package provenance so the dependency view is not buried below package details");

        var packagesUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.SourcePackages.cs"));
        Contains(packagesUi, "Packages & repositories", "product page explains distinct downloadable source packages");
        Contains(packagesUi, "SecurityArtifactSha256", "scanned package hashes collapse repository mirrors that point at the same artifact");
        Contains(packagesUi, "Repository manifests pointing to this package", "each package lists the repository manifests that reference it");
        DoesNotContain(packagesUi, "$\"Packages {packages.Count}  •  Repository manifests {manifestCount}\"", "package/repository totals are not repeated above the package rows");
        DoesNotContain(packagesUi, "ImGuiTreeNodeFlags.DefaultOpen", "package entries are collapsed by default");
        Contains(packagesUi, "API: {package.ApiLevel}", "package API metadata is shown inside the expanded artifact metadata area");
        Contains(packagesUi, "FontAwesomeIcon.Flask", "testing-only packages use a testing icon rather than a text channel label");
        Contains(packagesUi, "headerMax.X - glyphSize.X - 10f", "testing icon is right-aligned inside the package row rather than overlapping label text");
        Contains(packagesUi, "package.IsTestingOnly", "testing-only package presentation is explicit");
        Contains(packagesUi, "0.23f, 0.20f, 0.07f", "testing-only package headers receive a subtle yellow background");
        Contains(packagesUi, "else if (preferredInstall)", "only the preferred install package receives the green installable treatment");
        Contains(packagesUi, "0.07f, 0.24f, 0.13f", "preferred install package uses the green header treatment");
        Contains(packagesUi, "0.08f, 0.09f, 0.11f", "non-installable historical packages use neutral headers");
        DoesNotContain(packagesUi, "package.Channels", "package headers do not expose Stable or Testing wording");
        Contains(packagesUi, "RepositoryProviderRules.SortPriority", "repository references follow shared preferred-provider ordering");
        Contains(packagesUi, "baselineDeviation", "same-version packages with a different artifact hash are marked against the green baseline");
        Contains(packagesUi, "0.30f, 0.07f, 0.08f", "artifact deviations receive the red package-header treatment");
        Contains(packagesUi, "Plugin differs from the preferred package baseline", "package divergence uses plugin terminology in the user-facing warning");
        Contains(packagesUi, "product-package-baseline-warning", "package divergence is promoted to a red warning panel at the top of the product page");
        Contains(packagesUi, "FontAwesomeIcon.ExclamationTriangle", "the promoted package divergence warning uses an exclamation icon");
        Contains(packagesUi, "Plugin package SHA-256", "package identity metadata avoids user-facing artifact terminology");
        var sourceComparisonUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.SourceSecurityComparison.cs"));
        Contains(sourceComparisonUi, "sameKnownArtifact", "source comparison uses exact artifact SHA identity before comparing reports");
        Contains(sourceComparisonUi, "Definitions integrity anomaly", "identical artifact hashes with different security results are treated as a data integrity fault");
        Contains(sourceComparisonUi, "Package differs from the preferred baseline", "different artifact hashes are explicitly compared against the green package baseline");
        var productPageSource = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.ProductPage.cs"));
        Contains(productPageSource, "ResolveProductBaselineVariant", "product metadata and security are anchored to the green preferred package");
        var projector = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "project_marketplace_catalog.py"));
        Contains(projector, "backfill_marketplace_security_from_completed_scans", "client projection recovers completed artifact scans even when a duplicate per-variant current pointer is missing");
        Contains(projector, "plugin_security_scans", "artifact security recovery uses immutable completed scan history as its authority");
        Contains(projector, "_normalized_package_url", "exact mirrored package URLs can reuse a proven artifact identity for the same plugin version");
        Contains(projector, "canonicalize_marketplace_security_by_artifact", "client security summaries are canonicalized by exact artifact hash");
        Contains(projector, "validate_artifact_security_consistency", "projection fails if identical artifact hashes retain different security summaries");
        Contains(projector, "build_advisory_risk_summaries", "known dependency advisories are summarized into the client security posture");
        Contains(projector, "adv.affected_version", "known-risk projection is scoped to the exact affected dependency version");
        Contains(projector, "security_risk_score", "the compact Definitions database carries Omega's bounded internal risk score");
        Contains(projector, "advisory_points", "known advisories explicitly add weight to the internal risk score");
        Contains(projector, "relationshipConfidence", "Definitions project bounded IPC relationship confidence");
        Contains(projector, "relationshipReason", "Definitions project a bounded IPC relationship explanation without forensic evidence tables");

        var discoverUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Discover.cs"));
        var securityUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.PluginSecurity.cs"));
        var installUi = File.ReadAllText(Path.Combine(Root, "Omega", "UI", "MarketplaceWindow.Install.cs"));
        Contains(installUi, "Required provider not installed", "install chooser warns when a high-confidence required IPC provider is missing");
        Contains(installUi, "View provider", "install warning can route the user to a resolved required provider");
        Contains(installUi, "will not install it automatically", "inferred IPC dependencies remain assisted rather than silently installed");
        Contains(discoverUi, "FindRequiredDependencyAutomation", "automation resolver follows required plugin dependencies for automation exposure");
        Contains(discoverUi, "Automation exposure through required dependency", "dependency-provided automation is explained in the automation tooltip");
        Contains(discoverUi, "maximumDependencyRiskDepth = 8", "recursive dependency-automation traversal remains bounded");
        Contains(discoverUi, "plugin.SecurityDependencies", "dependency automation follows evidence from the exact selected repository package");
        Contains(securityUi, "FontAwesomeIcon.ExclamationTriangle", "scan findings use the standard Font Awesome warning-triangle glyph");
        Contains(securityUi, "Known risk", "product security surfaces a dedicated known-risk badge for OSV-affected dependencies");
        Contains(securityUi, "HasKnownAtRiskDependency", "known dependency advisories are handled independently from static findings");
        Contains(discoverUi, "Known risk: OSV reports", "Discover exposes a visible known-risk marker without revealing the numeric score");
        Contains(discoverUi, "UiBuilder.IconFontFixedWidth", "scan glyphs use Dalamud's fixed-width Font Awesome font for stable alignment");
        Contains(discoverUi, "var glyphSize = ImGui.CalcTextSize(glyph)", "scan glyph centering is derived from measured glyph bounds");
        Contains(discoverUi, "(size - glyphSize.X) * 0.5f", "scan glyphs remain horizontally centered without punctuation-specific offsets");
        Contains(discoverUi, "(size - glyphSize.Y) * 0.5f", "scan glyphs remain vertically centered without punctuation-specific offsets");
        DoesNotContain(discoverUi, "DrawPluginWarningTriangle", "the obsolete hand-drawn warning triangle renderer must not return");
    }
    internal static void TestCatalogCompactionWorkflowContract()
    {
        var compactor = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "compact_sqlite_catalog.py"));
        Contains(compactor, "COMPACTOR_VERSION = \"1.2.0\"", "database compactor version is explicit");
        Contains(compactor, "omega.plugin-security.scan-summary.v1", "redundant scan JSON is converted to a bounded summary schema");
        Contains(compactor, "runtime_projection_digest", "compactor hashes the complete runtime projection before and after rewriting");
        Contains(compactor, "preserved_counts", "compactor verifies historical and normalized evidence row counts are preserved");
        Contains(compactor, "VACUUM INTO", "compactor writes a fresh SQLite database instead of leaving free pages behind");
        Contains(compactor, "MAX_SUMMARY_BYTES = 64 * 1024", "historical summary payloads remain bounded");
        Contains(compactor, "plugin_security_managed_calls", "managed IL call evidence remains preserved during compaction");
        Contains(compactor, "plugin_security_dependency_drift", "historical dependency drift remains preserved during compaction");
        Contains(compactor, "--self-test", "compactor includes an isolated history-preservation regression fixture");
        Contains(compactor, "append_changelog_if_changed", "compactor finalizes semantic revisions and changelog before publication");
        Contains(compactor, "publication_required", "compactor records a semantic publication decision");
        Contains(compactor, "catalogRevision", "compactor writes the catalog revision into the production descriptor");
        Contains(compactor, "securityRevision", "compactor writes the security revision into the production descriptor");
        Contains(compactor, "changelogEntryCount", "descriptor exposes embedded changelog size for troubleshooting");
        var projector = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "project_marketplace_catalog.py"));
        Contains(projector, "PROJECTOR_VERSION = \"1.5.0\"", "marketplace projector version is explicit");
        Contains(projector, "marketplace_security_current", "client database retains only compact current security summaries");
        Contains(projector, "DEPENDENCY_SUMMARY_LIMIT = 30", "Definitions dependency projection remains bounded per plugin variant");
        Contains(projector, "build_dependency_summaries", "projector derives compact dependencies from detailed server-side evidence before dropping it");
        Contains(projector, "dependencies_json", "compact dependency summaries survive in the marketplace security projection");
        Contains(projector, "dependency_total_count", "Definitions retains the full dependency count when the displayed summary is truncated");
        Contains(projector, "DROP TABLE", "projector physically removes detailed security tables from the client database");
        Contains(projector, "detailedSecurityEvidenceIncluded", "marketplace descriptor explicitly excludes detailed security evidence");


        var workflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "catalog-compaction.yml"));
        Contains(workflow, "Omega legacy SQLite catalog compactor (disabled)", "v1 compactor is retained only as a manual compatibility tool");
        Contains(workflow, "workflow_dispatch:", "legacy compactor can be invoked manually for compatibility testing");
        False(workflow.Contains("workflow_run:", StringComparison.Ordinal), "legacy compactor is removed from the production chain");
        False(workflow.Contains("gh release upload", StringComparison.Ordinal), "legacy compactor cannot publish production data");
        Contains(workflow, "compact_sqlite_catalog.py --self-test", "legacy compactor implementation remains regression tested");
        Contains(compactor, "validate_compacted_database", "legacy compactor still validates its compacted evidence database");

        var scannerWorkflow = File.ReadAllText(Path.Combine(Root, ".github", "workflows", "security-scanner.yml"));
        Contains(scannerWorkflow, "Publish validated Security Evidence v2 snapshot atomically", "production scanner publishes the detailed v2 snapshot only after validation");
        Contains(scannerWorkflow, "Publish small client marketplace only after all v2 gates pass", "client Definitions publication follows v2 validation/audit gates");
        Contains(scannerWorkflow, "omega-marketplace.sqlite.zip", "client release continues to use the small marketplace bundle");
        Contains(scannerWorkflow, "security-developer-audit.json", "independent conclusion audit is a production publication gate");
        False(scannerWorkflow.Contains("omega-security-evidence.sqlite.zip", StringComparison.Ordinal), "production chain no longer transports detailed evidence through a giant SQLite bundle");
        var compactValidator = File.ReadAllText(Path.Combine(Root, "tools", "catalog", "validate_compacted_catalog.py"));
        Contains(compactValidator, "foreign_key_check", "compaction validator refuses foreign-key violations");
        Contains(compactValidator, "catalog_changelog", "compaction validator requires the embedded changelog");
        Contains(compactValidator, "catalogRevision", "compaction validator checks descriptor/database revision identity");
    }

}
